apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nightscout-secret
  namespace: nightscout
spec:
  encryptedData:
    API_SECRET: AgBat3hcygRm7334l3k+9RfQEo703aYhi6K5v+yWCheESwdryGplF884tmEeTvrwsuwosYIfoNLB72U0M5zQeCwV+iw4XGbMskgw34HnpBfFSKmOwagxpKDKWaPbUdsXNK6oYKyvutOACIxKfrmlEzNuKpSNrwzTJ7bULd24Qa7oLIkmfhByo/KMl6VgdYIuUqS29iyealqvCW0Ney/J1OId5eob8Z3jP7P+PlKxUQvBlQTyNOHp3DzUkPcIO61sj9f+tatAQX3eOQOcSvYDdg9neyvKvvLQorOHlJvWcWHjpSaOSPI0trIhz5IZQkQbp78/WVXhzz+SyaM37zycKL+E1pc53KsTzUKpRbPLPtmk9RVeJKjbt8HqO81kTYf06fAgWeU/vdCPta0r3grGXM0NvQxqqNXWlBirk9T/paJ1CKW4ugNjB9nHNqejhi/uOuR7FnRWQ3R+b2zQ5fvzswBupgadqLOqcf0/XT7IViX3pORXHS1Pjh7Rx9ln0IGHgbFu9dgARB/FbzzVvIWbYiCakBUZ564F6JswMlKTGmRYipvLgqoA2fUy0qGl14ekEmZSZg8XWcZE9WtNn/og6ZtgJAV+4YzG+kpadOzHAEd8MNXs9ys4+i34IABWD9waBZYluSQzrXk9ZiTNIJzp01sgdGdLorcqCwdG3kbwvFgHZC73s+sqZNbZ5sEoMIrnF35hYAEHWsptzTCLacbBK+UwFWvBzlVHNj0z/BeeQXhvWA==
  template:
    metadata:
      name: nightscout-secret
      namespace: nightscout
    type: Opaque
