apiVersion: v1
kind: ConfigMap
metadata:
  name: opencampus-api-config
  namespace: opencampus
data:
  NODE_ENV: production
  PORT: "4000"
  MINIO_ENDPOINT: minio-hl.opencampus.svc.cluster.local
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET: opencampus