apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: amang
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: AMANG Project
  sourceRepos:
    - https://github.com/skku-amang/main
    - https://github.com/manamana32321/homelab
  destinations:
    - namespace: 'amang-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'