---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: loop
spec:
  encryptedData:
    .dockerconfigjson: AgBeqEDYRM00hD9XdVfXStZs5Jt6H6BmdB8ChUmjF8BXDoXasuXdmU+ZVvfzQT4/YeqjJRlLs2aMGOHz+dNWt/uho1QI1xAeloFIWSYJ5PoZin+3IS7MV2xszklTsu1E5BsH9tBFhaRaaQp97K53YCwkId3ELvji2fvshXbX5cMV1qBOf25cuIy+lPpretLD+qXHUxG7CBMueW+X+IEJvDTc6hABGb2As6dDCVPDCxfQZj8n1bPq88/FgpwuhfYySgoivgiq3wSqa5eeuOy9XkJZwJUPV5V7cQp4/1VrWkXx6Jf4J2U19Y6w1Fl20SwtntgT5BMoU10olyyDxI+9nDoHvlxLMPb50pb8H6RnG6HCxK7tIxxXYd9PBoYELKWCCsSffF0iupqmwO8JN7QndZ4v3TLp89JAebl8TTtZIiFWCDcMlfRt9hCWbNPpdzXVQCg5lwznwX3UF4b7HSzc3bYBn5tHsq379W2tjpEFP4zp2CaxoXwcZp8Pedd5RPI4rUu3TgehXDNP4aKdubvu3GYn+mnXfrQceqL+MJLrfu/Dol8LefmaT5ihh07LZ1Va4Id8LoEnZ31WRHb1FHBvbI93YhxaitEvxy3bkmoc6lSOmDCVZzT1ZQ5me7XJTJsCq0Tg0lBfJqns3Fo6XRFWQHqEy54txnY760yZ0RdiaPlsQ1cRRXn2GV5oCFKg4vj4ETt/HzT18LPHAnn3on/lLMNK0dcAHuqm/DMYXZxt9leLDgSi7RCiUVfr84+781M7afslkaywt6ebYQzU9shhaJm3PH9Jv8S1BkCVGT4ZMsUgHHXQfUqF5ZeUxGaC4MyJ7QK4vgiylM+kyLZtQcUw5PjfIZYdkZWiLJGKQfU2v5w8Y5k5l8e1dJEsmvkzbmrv1ErisVeerDPKi+PoPZZoN15YzLxCDNIUfyxv8xGhmWXH70sDsiHBT4AUDUY=
  template:
    metadata:
      name: ghcr-pull
      namespace: loop
    type: kubernetes.io/dockerconfigjson
