apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr-pull-sealed-secret.yaml
  - postgres/postgres.yaml
  - api/configmap.yaml
  - api/sealed-secret.yaml
  - api/service.yaml
  - api/deployment.yaml
  - web/service.yaml
  - web/deployment.yaml
  - web/ingress.yaml
