apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Default project
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles: []
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: amang-homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homepage for amang
  destinations:
    - namespace: "amang-*"
      server: https://kubernetes.default.svc
    - namespace: "*-production"
      server: https://kubernetes.default.svc
    - namespace: "*-staging"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/skku-amang/main
    - https://github.com/manamana32321/homelab
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles: []
