apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: observability
spec:
  encryptedData:
    webhook-url: AgBBRXdO5VWj+TRS+hthLsgpT8LNRsFw6W/JuciOBQ4RSrCuD+MrLbxtLrJrc+JX5F0a9LlovLTGeqbeV/oLkgG/xX08/IwgBcxAXuNF8l2JPEDIGkVL4R0NqnCZeL+MwHUok54BuixlEsBD21ZWcbvUExI9y7x4D7VlSHSLkjo2bEujuDRZh7OCqL6IyEdZkhs0xncjFPVoNi/mllOOyegsdi4CLgwFDZv+xNVb3r2IcEXjB8KGYVbacOLgHkF7ymKNyg6a7TvYJ9c+mHSRv4At6ks03alh0d6977MiMk1DunWRsiFDBgjkJcW6eMrAx3BpyhR+DGEpN7Dfv3b8O6Tj3g2kJTllb6xDEGAX3mevwdHiewvFzpNu3WT8IFziI6NZIA22jv+FSnwfIrdelkElGWMv24RASPl6maBFxg9ofLXK3ouficliGKSmmxehs05LUlHqjTQl+p6EeeYULuRb1P+GpLz+XqUUA5cuAb498iaR8VMtPmdJhezO5J/UQic1NyLqu72Izobz/F/g/socNo9pPZwKXKCF40aUezyWqsakypYO13q3uMxoRbcTqQ7IwiiZkq5EamPTug+fpxwGfM4EvTXP3BzVdgo3PvGVVUAz6OeJBypLlOsV6749UFq7qKC1dnzPEXB1v6t3cdWUdOW76ODbK3yR7depWyEmu3yKg66O/Oh5PRKy3sgWKnQfaSfc1YQOSH5eNM0SKh92lJv8nCvvvkslU5sRgf3kTpMZ8bPYxZ3VJKWGsvSsX1VGD1cT+63Nr3lELjHVFUoApvGYngJbPUmZumoSkI0IqlODcKCkx+GPtRy6ajq3alT8n92cSXW/HGHXD5isqNlgRC12kvLB6Htf
  template:
    metadata:
      name: alertmanager-discord
      namespace: observability
