---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gog-client-secret
  namespace: openclaw
spec:
  encryptedData:
    client_secret.json: AgBhIeyg2t7FO7frqqZH1fUrzwLFor1YW7mxsGf1+sFUuGDah2+pHPedgRBSU/y+lOZ98zNd5u/irfLMKsfqvj3Zs20PSxSdCz/GuWEyKfNJ5gm4xZSuyWMq6qADu8BtuJ4lAdo6eEbhUCpM7y2yiZiIA+xN3txeHRrZ0gwz5zcB/jqiithhO/NEejq3xJfcUz+eaqxTC3iaFOsKS7LnDXJ32FvLYFUo45Xpj84u0hXDqgfxSUCWeX/muO/6Lm51pql9z0JGUOYQTs9KT1xBfFh0fzmtED/OjI0Jg2kc9D+lLkZ1I7qCB3KbU/Ft/ZDIiV77kRkXfSuGr2MgkV3lNRwNx54zayduAkTP8SFvgGL/yrjx3jFaUAQSmImj6C7T8GLF2+mdjO20fmuxnnNApPwwVHpCRQyUD7Funly9DpWsucRf8dl/OnmrumLMXH8dzQ2bqN1oXF1+oCmoXnFhOawI27PhJfPblvRT/hrNqPLRsXWftEmdPhbnwu78RKFpI+JdjtQArs9uw5jevUPImae2sTUPYAW4tDzIyJpv7FD3YRM7gjwaW1Qj3f18E8skztq0hUdXfiuU/8wQEO1C6ODm4MezNrgxLWhdkLQ2ch0i8ZywORXpVB9SHxQ9KEx7F7KCCJttphU3LxA7e01QofRRaXqU6HbRINT44IXAP9k4P06Rxi9Npv1iOFks97YdzL2TCgGPlO6C+4QawHIkjbPwk7xVz4XpeRf1+Bz8teQpy/xh37FZFqQkUugRMkxKjgM1FWXgXTxaSIIRUtj0zfdKFYoVCndC+QZIA+8F2oN+sX42yNvHAZ78W+0WLrG6JcZafKh20o+HIWXC7/OBUUhBHIa2SHxEbM8nOSzR9l2IC2fRs2RFhu9Ho3vT3AKHxR/Z3i/J2zh4ixEekY8JddSL0VvY0tC6zhAQwBlqChJW8UM8MjrRm7hr/BCZh41VPeVNHRNrMf4QT5ghvwm5jbtDI+q3h/Pf3iRFOnraX+mI/Xwm8suKgi4NSyQapuOi+sJvfhId0Y/fy5dSAdxIrkbI0xDWBROMf9c0xQU9CqCfpx6zbApoK0VGnO56BneqDe6iKnx8re7uVZeAL2tdzkwSWYECgRo2ZdU+Re9HMBW9WKc9ZK6ho5mikZHAaBgr8/373oyjT4bJVyHb3EdjSgifpfh6VZfxnmRUDErY4gAKhXdbyM/6UjlnsKeS8OqIeAtevsJk71yHoKgioSd8tdPmZpY=
  template:
    metadata:
      name: gog-client-secret
      namespace: openclaw
