---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gog-client-secret
  namespace: openclaw
spec:
  encryptedData:
    client_secret.json: AgAz385xvEsRoqUmUDVL/tTShmoUaJKgCfy2rBUorGd2xVZoXaOEV5nOf7rwhWYIA/eFyNBChys2Asp74DL/tGLOtVlCyg0rvPMRtUni+ZVlJobnRadWAafajXYeP7T4L9TbUJbS32aXF4kk1ic9aFDczfWoOyvdtTsRxfvV1eAzoEFyQqW3K0JhdpD+m+TB3oZ9pvMBb6dod5QV03kTLELLjNSfFbj2gSeUXV1OR4Xi6HJ7NijmHous3PdHK7deOecqpfpNZlfd/WMD0YGdusP/rE4iKdSTvBBab5x3B9br+P7xQg5bC4uHCKMqW1+3WJ2QY2sAxNmX0+dNzXIXlKrVW3xIdvyy+3n/zXycETxbSSExdrM5cdHZwdlF22y/dmwQtlEnHoomb6CLLZSrY9qkK76xyLUhRhwHjB7dW7DRgOUU5xkPSS76R1TtZ4yZhtTHQD4TsgGfR2FLXCAEc54kwOo/UfQv8ezlIje+yPan851Tzwy6Svlw3qQQwjdZJZtarlrEsJraMdYuqW58e100VZ+vu2sooC4XB0iJ4x2yQu5V3OCaE78rxRRLa+dftse32BDEp4WCVDvdCIvh/jk5zeYY/7eka0hdjC/rlN3wGLHAclZ0gpxn9v4xgkJDcLJ0fg9UXcasyPJ1/i7LBO0xsc6GefR9CqNPzTa7G9H0mHcEYo3knzilnaGpIQcDCSu+o9fsm00cjT/AZ5pPiMSOkNrsmRj8W5NC/zfAOrRyuhno2151ZJgT4NgL9nOBiHhZbjrl22HUVLDByLObm0Q2ZAbHyfcm5WWOfn0kwzhWfairo9x/av9k/RqGRStCR9uXSje8gUTaMtyttoMnGsZD20JeGRXwCs7mEQhxe0XQgPh2h7HOjj63hQKndu2gXSsJEoJY8kv1qIZHx5443vkQubnX9ctS7I1kSuUX9oRnzfl1jhVvyqLCeojOCt4/pXs6Z6Y2wmHxqiBQCzIenDgWRQQHdPOGTbCvojkBri/b1d2bnChnzEPrNTLXAHEGdWkfbcVTCat7K5+AvMduY9g6spbItW4408zlyIBgZcqPeTO7c0zBL2Ntp4wlDbkTUSgkXZGGBb5LNsTsOVcYqExhuLzVVFlryK9i4mpuyO2bijPX8XfX3YuWDC7iqkq5gXb1k0Vt2/5zRNR8Sn638vqJjmh4GZyzgCU1K/y1YJLo900zfbbsPnzwLbU/CxfKqmy9UFu57qtqs5v41KA9adKFYok=
  template:
    metadata:
      name: gog-client-secret
      namespace: openclaw
