---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gog-secret
  namespace: openclaw
spec:
  encryptedData:
    GOG_KEYRING_PASSWORD: AgA2BAsG71Seo2YEsa7aK5VHKZocwHM/yHGt0A4grooWSsMYnWIMIuBeYm8sQIwgzCtm4nfN9iDAamAWWcDmfhsVFav9y/husByOhB5mRCZ1g5tuKe4azUtrDgSnXSFA3anfCCIV2IZ37WZHejmRlhli9V3VkOjugdRrVY4G4KO/miFd465vD8Tp7jjPptQMi2o+d2h7byUhQysFmhbU5CaOA2CgXOJPzrH5V22jrpez8m+yc0vDGOpwH+J2DvGukYS1X70LgneomAy+4xONazZPE9Vvv0cMKBxE6RrCBHVdl8/yNDkZB2S4AtwQ8j2zlXfRzpCC2xCnn5W5SsMpyikRDaPyYbMeiYqDQDYNGmTVON5uvjM8gNyA4DlRUQkx2v7HnZ5oeefO0lyC196F+VkFejh8U2KvSGLXrSHlO8QO+1FiCyzyeNn7xkgrjGup8PrPyzr0iEToG4KuQwFV0VxZUlHknuKzNxbMnkaF4bFQIhi6arZHVmOsdL1nwPuZMia6YSeHL7d8JMHsXvlaG1Jx4FxZ7deznxhyrW2cZpoXG7X052eOe94uEbGByxOGzLpnqbVoaMUZuL8bDOJ8SMJY5WjYiHhEL7lq8Cc8WGKF1KibzBjKer0AmK1VqRVr8DgkqPBoXuRVKlUjU5YggZ0MrRPwcDXVa3bBK7z0Y409DYtFW/j46iGtMViyJDrXH8ANQj0CNjyOugZypufiqd9JmtoWytBFKnjQR3m0C88+NQ==
  template:
    metadata:
      name: gog-secret
      namespace: openclaw
