---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-backup-key
  namespace: openclaw
spec:
  encryptedData:
    ssh-private-key: AgB2sgjamgEzgLQC4IGyvzO4Mp3lF8GkV+qkYjLMShb9Jwgk9fiyBYXUlSHi2UaT41PiTin+MOg2+J8ukQ3ZCggNJUWytkXHogynLWsR1IxjUBUwo76lwPWOcWicGyBhiq2hDg782cAbX4Q6/lXpRowWaDgy3KBXnYc34+/nuRzllpPBLKwSh2yedwWD5ZGzDCv0ZqUzf3EM9gNQPufarPQF71mGKE5DcpWAkwBjEBqQHtgeSSkOr4jkbAYoWDLOTy0gckAMabRTUiBoN8iIcLy5wevWzG4m1JzKLi+xo5XS8qyIOP5SAgP7BO6aOaZWq97SAcVLPb4cfM3KvkWsMTOwW6lhf2rMjPp7xdiOEhryRLh40d7yEplu38IpGJwMtE5cifak24+tY6hRXVEStvjexospVIET3Tdl833aU0Lj8ObK43uLZcn+O60x61JXE6JWzON/XSwBQ6IyarIcXkfVXRIO+1rdEmCAYlvW2o4ANF4FhwcUXJQgDl1R7P+bCPllbmzSyksTCKtQTCmY0liH3ruyV9kt4FkLDA/7kd46UMXdkXIpzLXD+nJSw6UtCdBsB1gy8t865L9x9naOe5t+WTxhAC7s9VJwrbrk7zndRD01tPxPjDubms03aNhy+I4Z+o/hJhXgexlumOXC4DOR4noFvpVtFUWCzJaNPv2UBUSdi+rlt8OlVcBwkkTAhJ6nJObQ00hENxCFmgKozL9lnODlG1Y1W6GWbHtlr0vUBn1AIoh6al19BcW428Le+1R4t5880L73/VfJ0ibPxHZdVX5s651+ib5S3FH3TIBrPhuxjKZ1M07KuDzxjasTvmVggyNA7y/cJM6/kJZ+NaTesZ8Mp44rvuySZe05CyuZl6t5fUvRi7QuDus6QDGXdW7j0nCaJkRJ4L2ulgGT1KNIDPEQjc82UiLhUEkOsznfbIOR/Vm6nfZwf/CTpS1o7tdDMoW2AkRf6ZnYorZMzr9M+tk+EF6QHkYv94JLUtvnORK7ePj/ZJtrLMinIWoj5Zc/wUwJtoobrGXAS8gH5nJAfEMO6Yv/FeQFZ1V39/RDfkckm5wPKVTRLGxSldFuL38lWyRldoL0nNNs0cWDUv13HbZyZLLzL7xY4uLQkeXdAd5cUQU0zUE3oXUsp7dBgMzMzTSmeBIv5LspXYkOLytd9rMO/rBd1bF/SuPXtGQWK/FY+13mZraDHfOFMCAlzOn1v+c1mRYx7oFCNBTKHzs+wDMNnYv7B5Y7IfWc4KOqIIV0JWc8eRzL+KZ+m8Pnt0s=
  template:
    metadata:
      name: openclaw-backup-key
      namespace: openclaw
