apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: essentia-minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/manamana32321/homelab
    targetRevision: main
    path: k8s/minio-tenants/overlays/essentia
  destination:
    server: https://kubernetes.default.svc
    namespace: essentia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
