apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencampus
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/manamana32321/opencampus-api, web=ghcr.io/manamana32321/opencampus-web
    argocd-image-updater.argoproj.io/api.update-strategy: digest
    argocd-image-updater.argoproj.io/web.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/manamana32321/homelab
    targetRevision: main
    path: k8s/opencampus
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opencampus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
