apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windmill
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://windmill-labs.github.io/windmill-helm-charts/
      chart: windmill
      targetRevision: '4.0.134'
      helm:
        valueFiles:
          - $homelab/k8s/windmill/values.yaml
    - repoURL: https://github.com/manamana32321/homelab
      targetRevision: main
      ref: homelab

    - repoURL: https://github.com/manamana32321/homelab
      targetRevision: main
      path: k8s/windmill/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: windmill
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
