apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - s3.amang.json-server.win
      secretName: minio-api-tls
  rules:
    - host: s3.amang.json-server.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-hl
                port:
                  number: 9000
