---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: amang-api-production
spec:
  encryptedData:
    config.env: AgAg42btZ2DdPFehG8NVQxX4MUiuyovSvCapOqCbmRKkP8ZWqTWaSyuXPSLK6bQMpYdW7t1QJFCzsUFdY8mMUxkWXpKHHKfurxXMBqi3RMEH59Ut8Q1o9mFhhM230I2BwDWC2Uyvy+oDXdRzvMc39ldCDVttEb6fU7f+D8CRSOehTZsXxNhYmy0sIi3AqOZ1pLOjKhpz8o0yAYYqkgSDCjqDtOAK3iXU7rxLVhUHycuNnAcFOjfIjnMVj8nQgTgnUP1xai+ri+R7PqxeqV9SYnStKC0Ml66ITPb48P8/qzh3QIRA+DuNMmqGQYDjB2PJRWlpMYVdJG03+eJI+bbaaYUuBCk6iCcURGn0OKDjMmn7HWI0qUMzYrNsCA9n70u2uRM+snsh1dAKR9YCwTaYR3zNJJYvTAMBMet5sUNgqS3vXIrTYttjM6u95HvVJlLEHb2t6aZCVSxoJTp5O13sEobV/I43WHZJIbEU5ntNPk7CyP9u+b59O1WJ4GIMDcKNExDkgMQO5JhuweUmHFcmDYwRL48OL5q1RR3KVZpZAFjA/28AYabsElpuQSwzyXzWEtJaaSXWFllTfF7GCRQMxeHuQql3B0p+gB9BTGQpvjQoE7Qfv8U6yjokGalQfIT+q5kd25bJdUqlqlz/fzK70wLGf5YV1q9tmM1kRVnybM74r2m71qsY70es6h29rM7zK9ZKs5hMzsDKOwT3PW4kdtLvMXYxFgweKhxICgeTcDZ1cklo4BwB3IYzvgqPW2fxPmsNRVMjfBeluS46rGWizwp5cgJl+Q/2uT/92idcChw16HaEKzYQ8wtd80Hf2lnqnimR9Vo=
  template:
    metadata:
      name: minio-config
      namespace: amang-api-production
