---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-s3-credentials
  namespace: amang-api-production
spec:
  encryptedData:
    S3_ACCESS_KEY: AgA6lnG3KcCIX78F6GUXqHUBgKP8O9n+ITDcR2pqwaYhPug5tdZdrh42MHTAj2xemnoRTZSdsE0FI0UtjUHZKgh4l2yRDRbBNZgGgw/6NfvhhiaftvMIio7MaTKxWViejKhj75HEd0d6tojDNdGSB2BJo5Xu8Jt+H1W1tbevrd11UCP3DBbSEAS9Gu3VBCTuYEWjugzO70wpZxwMZmHR+OFl3kplgr8t1HJsIVEJsWgT+FnwHW2UkryGW6zY4lVjzaJdluxgWFt4EMtrRWpLOHKs5esJZ1o9LpN1nGol9wtFEXbY1L4RlBA0AeoKSoZl6rBnjGkE3XhxNmg44NwapVCkGfpr83/3/0yz3hJXbi3zGu/mexGRCVrSKnfFvbfgyrXPBEZ3eGH0Lq17SNMqqBzbhgi5wc0BC2LsHvatzaBxOMFJ7xBMQ4sjOEKFNfvLHqTN91YiOXKcyoFZuCaoo9WcMIu9w+PNidak8QiIogOZlt18ne9YHbCFXj0Ah8tXPxfWFVpfODGZr9b41x+ixU50J0Q1IOVF4CpA4ED62Qhb9N0MCK0cXv4UkIX1bFGQCFtTuv2LT2Sgy07tqY4eM7c03sHkyvOMVOBEghHrLZxt17AXiFRQDGoVQzurziLWy1Qx5zFtbAjKY40Oow6GsPVgmjz2u99y10FOC7dF0gznCGbqfU50Aa5Kxqk/hoyktAU+ZfEZI1oBFj3P71mvUTUt
    S3_SECRET_KEY: AgAFcPPYUZ+3XxyZ4veTR8zeuNoMbJCV0S/Y6DtmciaqS9as/OSJpv0C+kTLbc7FB4PGm/Ixjgje0sOhyu0mZr0Rv3oU4H98feOwS+SsUIf5y3o2TZRU0PJRExCgJJpjhaQKCXRRRaZAjCRjuahQGJqMW1aNAM2V5+axXCYppWjjPmIMh+RZ5njsosRikXcUOSPbT2xAVar1TY3C2+M2wxCiWVKqNdA36CJslV0+yvS/XJR/0/cGB/Cd67rzJ0RllDXITO/QTCV8B5wLwc2KDp0wCBCd88oYwBYai/cgXmEh5bqdsksD8HvFldEO+mf58PPWf5xnjklVBzpL1XdRV6I2c57yjyDh6o/M7i35tXfdusw7abc+aflC9tmwYsy35mW5D7CUdO+8TfCxbziDQ90F0UvN07W7M1Ync88mCR9HppnA1ROOXLm0mr+9SQZqs1eG4F6lmIa/Mr8EN6Sk5MmPtfw4krmXskRslbwCNmhPc4bo9DJDfYXF4h3LfKAb4Faqf6enO9XRlkGqSacYRI8DqpUNwMuECIwUNhSmk9qjGpvgkZEl4jf0ey+o+/c6ppBb3kaZy65zzf4VnMTIqE05sm6FjB2Wgv7qjZtq23YSpHP3RtNfr8fMuDYXwpq4srNxvuVEzVa4zMIx6alFp2ffDVJ4bZ9ceDSCZWgWT+ljx7dsnkd0bx6QMYfY6hAs4OvNPINitrYLtfJFlIiYUFPyylJuAg0zmUEysZZ8G2LsJg==
  template:
    metadata:
      name: minio-s3-credentials
      namespace: amang-api-production
