---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: amang-api-production
spec:
  encryptedData:
    config.env: AgC4rRybGsyftyXCTUtNv+i/FS+eLiTCG6Rveg/c7yKZjSaToT6jEEp6kimW1ajmOi4oAn4Uz/u8duTlQA/WonqP8dSB/S1cWLyy4clKUKVFGQA/0/dzPG8eC+GbebezS/T0jRhsKdb5+U1O6LdOxKNAEbk/iidp6ifFKXodX3jFOQPRBcFQ0I5h6dLTnQehp8M/OvmNpYY6c7LMRacvwz3UsvcIVcLRzQ3UKSVFktc+fN4KXuAjx9eMjoBA9T0gWKCEj89gPBWZYH6DHexMQH2pq4KCZz/+9KtyGdzxXpCizcO3SshU2QCI8U+dVhEa20Wkwnlz16EY91z12nahw7fLWA65UfrmlLdcRl/eufUdxDCA9ftUAlfDwGLAysFpjL3jNHY4W+/eT89+ENoo3VfF0rJvKX/WkE9k2CIQzRJDu86Jjf6zqMrc5rhTi8pSo8PtHhoZH5m+DL2cXb/v31DRqQUUXiQhxA1iyexiPL0joB8iLalf6piUfkggvaVJkZFTyEEUtRUuG4Bbr8/zgCpIPXz8/WzmQbq1+XieQ9S9NTpaN24PDsHXfdF6aSIDUaXHB5BtD/J1g+rlVrbkVS5262k9pkgRp5IEdgm5Fda6KosB/Tn57AWq0drgR7AqT1a+Ujvw0Ct63zsHN8pbq4Gsy8TwomLFtLLRvCqk+tl9+yUTBjEAuCeJ3D/5Y6AeOOdwgiXWfv24zpy75iD1J+srPmsHrTs4oSSB1RLrvK5oR7CXaiuxjtHh+av2ctxeCdXVI//59iDyzABNrPziQQo0hnsJLM/bflGuV5LJixawo1dy8T0mu2PNHAK+4dkvBSiLYh8=
  template:
    metadata:
      name: minio-config
      namespace: amang-api-production
