---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-s3-credentials
  namespace: amang-api-production
spec:
  encryptedData:
    S3_ACCESS_KEY: AgAhD5JXKoxo9/gxduNduB9ed1QUoBX81iTTxe9F5QLcscfZKuFpV1wPthPYoFNdhafyOOWjAx9uKKIxUy9m5CaDaD9Bl/K2+NUWpUeFwRhmaBqSL/floPvOmuHiYJB1/uzZ2HG809fyP6CV5Bm9RaMShRDGSXfaYcfs61FAGVazZ4lpHNyyEhCH4CjZh3cQHqx3c4o6lUmIycc1v/cs4/jDvEYDZBSnxF17K+iH/2s2Gtz13bmbwRl3teZrb59vxPAQdWthLVihuP42O3Tteo9Z2TttN3FDUsuYP6o3Bf8pY1t/FI85u7nmEw1oCJ+DXCeOMQFU0paPL5ZlxUNWEDU/q+fy3OKYIofIpHJm483h/h+MSiYJEjPnkhZOuHgPiRDjwLj/a2SItOAlBgXIeN12CumUHYdl5uqRofFY5nkKZMtVpdTru2CkR0LlWSUFSgbtUkylscF1kYE6q7JHyShyNvKTWtaInAALAMNHwngTOGCqc0R6zscMPSvs9BtG753Nazk2YdSgqgcrl4ltXlzNi35POwZD3sRIZhVoLf6R4/9SeglaMGizdTkWl2/2p5/wfJlQ2uTKLF9iaHzo3TdPNGQGHo4YMzYwvd6c4O0nMEL7cp91Pu5vtTOJTrksBOaW/9Ut6ORK+mKrZKfTQCakwkJ2dZf09dQFTJaXNafGRYocMBQ9nPfhTr5yT2Y9bPy5CjI6qFeyZBFaghVaS59u
    S3_SECRET_KEY: AgCi5rVwCHEd7gZhHejsPB4t1vQjD/TNuCIf2CCGQlTmHc07bpF3OsG1neX0bxS98aB4fMg4n6KGqwPoZ7NxUJ20Aa9WhZVX8wWHEUVhlMA5NPkUX0Tt62YZ6yUyQ4/QMgzt/PuehGWPAdl12CxlYCaGZV1EMQNLgNQyZwGd0gwKfG7N2mpT2pCpWd6OA8HlTZ5MEXWlosIHrhAsNM4Iaf8OPLB7ND0esV2AwbgYzmDAEhLJ1NQLCckL2l92yugJ0UcpIa3Byvh24nCmEbp4ZIbqDNaNtAUsZiTQ81NofmeI9xay0aDvttXy8bQF/OaEMWKwbv4r++EP1JY8Im0mUYKd+wQpLfWAo6eAJYORE2VDjvant/t005KqkBJTeuG9L/TM6DlLXgS+PED6zvQ581tdt1vUULC2sClwgW1CbRTqg3lTwPkp+8JlXwlDTZXN9sVwYYqHA90yQtpK/hRj+0VERQiAEimdpm7ajACC7x1l/cu+fqqq42ESFHLQ05nf8aO8+aAvEnPntcrfNw95h/Nai+q5NoRMwYF9/ZlgbPvJdLRbHqTyuLTfmHS4WXKCU0JIw2nPvTuc9Vc5fCQ76LCaIk4j813N8SwNS48dfQL8sOV4yD0aPzCHo+7sQXqaqN3AH1e7w2gWWDc8WH/Qevy0alMOPUQK1QRPx8+/NPvAnnEE8DZ3MO3qeyT12sEYIRPeORSVn6+EBukW7QY5SSWw+yXYRyQvXPXF5LNRHyu/7w==
  template:
    metadata:
      name: minio-s3-credentials
      namespace: amang-api-production
