apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgAB+xUXUrnCjNRw4S834WGO2/xPmYW4riWoLeKe3ySVGxrwGAjMCMgPTGvPGyMRsZ0oMNG+jK1tSy/nNtTfYLDnZninpXl3mq9cFAQOEZAwz9Us/JbENCjthU5OocSy4Cwa595v0b75BJGR9k4rLBdklpeW9zx5a/bZAK3psR+54+GZmxOcr9C3488yPpHjr9I1rLS/VCV2FpKjye7OhUPP7FSP9/qsyQ/zimvqKjxpPME+tMvww5VZU/bfxrLXZz1hp1T0xZFcpKl/rivri1QS4DRIMwR9wn0RLKUiENmoTuyRdFdKNlj2WejZ3gL0puoqbJPx1zM0ATMNVkBJ+2SuX1+uAQTAIeh1KXumkUyfV4z+lqEHF4MBYr7MNaERLFEXUId7gDSZtT9IBDa3z8JDZVD9ssIUzZRMptez5s37hiZsJKiQCZi0QCqNUipMk04GNEf03OoswIPM7ArTvlvbtfoQG6ROBd4D7wvapM2d/Q9bZZtcAShmGQ24X1TSU8Rl56jv2ZvWyze5BQva0NsDZmPt2/Mdb6DyXZ6DD6iI4AfXlAV8SaVs5V7/bwnMU7McjDh63zJREc+g5Umu5wQWVWHdRj1UwWB/9HiMy36RELbMm58P2yGU7Sl0ccTbGmT/X3RKRaH9ca9IHROrrPEaVw9IyCkDUPvaTOBOgc0Yn7uXD2xAH6bBSho+yh6VLeO75QCwX4PeB0IpP2UnhGyat3UVnX71re3s7RHMGVhGZRg9aMHc+I3Rm7EPNiGLo9jByIGNDgs6r5bqqlbBnUsU
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: crowdsec
