---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth-app
  namespace: argocd
spec:
  encryptedData:
    clientID: AgBVP30RpFlUTEqSAJ7IRwGbwYb5UpoA8/AqtLQmkQnjTPp1/LKIqiLm5GPEzV6DOleURyrWTIpIA/MSTBbT0vMkH3cZ5qPdGgbXRel7KspOjMmAkdRDsnFmS6ySEPIyMyN9XA21ESjnpDJZdfQUcFBRnUQtyRXQKGWjPh4P6jE4ILpiNfuaL0f/wy8Y2DCPQiY4O0fHFBPx1QfXdOryi+YZQY8SJ07cyJ0k9RGUNASWyMgiSSU3FM7HKAbURRMdAKaXUsyL+tQdbGu4719qReznjrPpQJ/fNEe7ioEtUGGEgK8aOhfMwS6eleU8pZLGLSaWAAtuC957MZwXGLjxHvDGQrfqJA5Z1wIDciD6HNMc6AOr9tLAS1RBNcfmKwF1p3KHo75OX5wArImyLzHq66IbUnb6N+WyT6XWn/CwAnBO6GO3m1YY11p+mAfJZPJFfeL4tWFsxLNP4WlrKNd2rFjPoVPRDnDKTK2kVosZhpT3gm6udBTTmTVL+nlBHU3z9pyrSrg26fPbS8rwxTFbo9ou8bqRgDQULDx8oDEP5h+3QNo8Nhvur4hpBYaaP3i8bpBbWoq9F/flqK3RlFGi3clrtD3+mDfXF3x1TxfWgvDlSsNaCOUYgVHO/LWdHWpC7SFAAczfzdEnrzpjDLIxs7R+Y9zUB+pNa68zqqAnYyCTa/+Bq7DLhC7qjsc6fJdYz+yzDLfyWvYzq26SGbZwS1B3F3cIMA==
    clientSecret: AgBiTDpAoEOR6umuINcNoszbA7lOQLQ3io6HYXrGx4pRzboSsLhiOX+bReJZ8dwuTsTMFU7fakmzSJPZeKh965kHNMT0w/vEUNfX1URbluy6XuggYvaq1dwhHj0XjeIKOWvz94zn+0JP09hJxIMZBnS0aUyTTA/BnmTtu53mzTx8GdOSiaY6+co11ogw9AZx/2Voc4Ea9HSrJiQ3uqsTGmQrWZJskCSwAzJ21adeJJ2H0dFKnQW49UMXcPMSwN5pf9SBvrOi2aqvDAXSrzm+fiGKH9umj8cSoR1DGTNg5Oqu9QXjNIWuMlimEtzhb4s4L9dUlfVSrohDvNjweXpp7s6CByvLnmMvRNDNLmzLuypml9EZNtt1P0mbayLbr1EVSQAok+JuzDWBz3PovY2LYmUX1mjp5oG8oYgDYtLuIF2sQdauTp7wlc5lQjhZTuxFJ2/Fev6aBFF9QokP855d5jmpTI3Z8R7zffi9S3lopG99YneS5p5w69zSttKbvPO1twAa+ohstJb2t+S6eflFUO9vmu6JnFbdPB776WLYQrqsr93mI2ttXVqKp+bMFvGjV1JwTN5fKpECI/vquRMIwWazug9gThwh3EUJfT+81dP//YcVOn4cjbLfPBpfeA7vlzYmOBpQQ8WQQeZvKBLfMq4MaJ0I65OjTjskzN7u4DhadxMcz+eM7r1xeqCqlMt/sXPN+BEor+PbI4TfcVAjnmw4a2A1FSoav6JpabPZQFJ5XzwNpBI6cCrg
  template:
    metadata:
      name: github-oauth-app
      namespace: argocd
