apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-rcon-credentials
  namespace: minecraft
spec:
  encryptedData:
    rcon-password: AgDKdHjj2piod1TyET6oMPWgQNDs6XOMeWMPcFHSGuF0UO5Kp34rf4G2bYufh1QZjy++kgUJuBMwcp9H62v7LfBHR5m3ae4T3asoK1IvYqwNcGqEe2Jji57Q9vp9/0jSjkfe5SAppWeHZpaGpmv8cxu/3HP7WxTh/eZG5k/QRAEM9QoVZSRuaAWQ4VLGfXISPoNeyyU40WKVwJcsQG/qE1NurtWmIqQUmx5oN2hkYX40bFNZn6J+31QTPFrQ7iVZKJOeWcGZm7XdNAEVMfdvvPfu89oxZADZODsoZC3LaJ1UyusFy9xlmRMIF0DpsI6GPD1FWHpTVIpTYkFJ5q2QtSEY7AQJSwCwRVZg+sGdsvrzPotk79bRgDX2iU8MCV2/KuuvrlSo5Tg0zlYP/tBeopWwjxvGGc0EBpKSaAIM1apmqv4Dg8UtA9XT0J1zD3h5uiy9PWZvW9jxmLBIn3EtBl+VYvyEGzIKEu0dwm/nfomPhnBz8H1he3i7THvsgQwnm4ON9f8PEumRQfxKJY6mh5ygEJdmLb6BG+SQ9aQeOPSTArkrVo09v+DetKEQpuky4nmWQiGObVB3GXBs1KERbN5w4La9l5c5/hRbfskddtSHnE/F67+Qmmh8mrUgLRWJ9GGQkJSDnT7ARLkEdqCD2lqC26ObsYnNpVQpEJ3x/dEVPdOPWwfbDq93tguwOyxn6oDDf30gb7yxH5+RtBJeZB/4+gfuWSN/Fd5+Z13lrvh90nd4lGcAVeoC75rFAg==
  template:
    metadata:
      name: minecraft-rcon-credentials
      namespace: minecraft
    type: Opaque
