apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-discord-credentials
  namespace: minecraft
spec:
  encryptedData:
    DISCORDSRV_TOKEN: AgClvjSXh1rksborJdZMo/ZEs1alkAQuh+PBdLXIPAA5fGBF4pFbhFYzOLy5QiNEdbn+sXM9P1BAJghmDRWOxeudGhVx4a2UGsYE5HAxJDv+CyflFq892Xum8r+lA7hoFOnc7375590bmGezUrKwJ81k5GcgNuxsK43OxrStOLG6lv6uOarWoHrvEcHf9O771p+6DqK6tIxLJXJsz3cszV2TyqiSUvhmx+ux6pH3BdcjYYQwM7lwpN4DVWMtHdU7ypiKt7FK6JK8VVuxABGlsP+1vyjnQDoHpJPZYM4orGKVXNJ6y6UtmvVEB95/q0hC7DCPKijM6IlWG/8rdVUgxyu+NqyNeHxmvvkxo/yb0x/hG8CLkrKBu/nSIlUpjINfECq6fvPt1+NbpbaMm2tipNSoSBKY9aW1KqBpRuWdEEo4aorsCvOKVWyZHsNU2gUowuh4jhdMBZtCkVeuZG/KbrSqnJVE1L1iRS0NwOSRUXoiVfZ03oOQbRGI9A8Klh4ccn0A/UrBpiGzjhzLqlqT3fmiYdZPnzwfTcE1OFoIopOCRUql8BxJ9Qh5k/QGByfrCaF7iZ4xuECOk3GUTgThzbaUXClQ20AntbKUlnt3PJ1aMd4tfG4kIcxLvTXA8K1zK/8c59yZ61/te6gvsABVw8n8LNmPLisFzSdjTD3TuZlwIAGFlb1zikk4sKOOP2GBQb1ukkHsFZB5ShGtokViliQmn9U8aPkdhwbJfSy+WTiSY9y1t3P22EkNAOeETLswc9h20Gx9PSWuCwaZZMAK1uti0d/84gq9MZM=
  template:
    metadata:
      name: minecraft-discord-credentials
      namespace: minecraft
    type: Opaque
