---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: opencampus
spec:
  encryptedData:
    config.env: AgA6Pvd6yvdeeB04TPywQzM5kx0ghHf8HenixHue9wtlrvQQlxR//s9SD1Wq5SOkVHrdWn8Y/He2JoZcDCQ6N33eWTFj2qUCxqjTsdazQv5bJZyVrqo8dl4VLPw/gAySjpz8twBV2Q7r2pFCIWZoKcw3A3TSEAA5BqOpeig33cHKgB8+4LVDV9RBPlRZZNwnasNJy6XqLOK27Ulrc/YAQSvr87xLseMGC+TqPNaf8Kx/N3DpxcQRVjBUW3iC2qtYJ6FeeoRgd5wvEp19LzNgcot10a6975FWQwBKrP1k66qGhhC+USzvf+xqveCo9QQPtMf7B41OBaHC1Z0QT8lgV8eCOnc/qfiKledaAl0AC3YOo+PS1/usEysG0ifqDd18xd5GAwKRp57yW+2jxypEBx6+XvGIRfGLI/+ld7MBzOpW4XEI6gVgPEuwy6g6RQmfoOhwjIJBpDHr2BLFltkZjXkCEBf5+CH0Wr+GJtsfaoTnS44ip634FbeCu9nvtPCsAm5vnJ2puUMeHURa4MhkGkxSzzKgHWf2g59NZMIZSnNcIdA4jZskulpNfvuVd0aaQRTfMPZ+6+4kOWpvBRqTZX4dgfQs4/gB+MMt9dbnyfBkIo6++WR+AO23iABmt+w0CnCsSlpo1hgSG+B7872vbJU1uZP4iJCTdSchvPrlNfx38iXiKqzEoP+4C0w1B3MCfatfsLaY+NpwXvnY7isAmuIgAw7mTMTc5HSoIzZeK8S9bB5YMXjiHUvzH+s3SSPOeC397VxyTt17QUgou8L5INMhzrTxSlgy+Oq+i+MYkAv7G8eHJ4Lqrw==
  template:
    metadata:
      name: minio-config
      namespace: opencampus
