# TODO: seal with kubeseal
# kubectl create secret generic minio-config \
#   --from-literal=config.env="export MINIO_ROOT_USER=admin\nexport MINIO_ROOT_PASSWORD=CHANGE_ME" \
#   -n opencampus --dry-run=client -o yaml | kubeseal -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: opencampus
spec:
  encryptedData: {}
  template:
    metadata:
      name: minio-config
      namespace: opencampus