---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgASKenBXWIRu+rHQ1upEJX3wTfBqRjSNa8oGM4xlelo2574JyG/lZOsyIvl3MUpJpyd0fSB1MLVoMuLy1zmEAiQE0tFpymCHNTpfX8VW0ikM4KW82m7RZoIA81pYQA+o467FiKvjfCKmy0nLTfsmx9sOB6fe2maoTe8N8EQYb1fQf+IzbXg0iNBTgPeEFx5TV2sx0IhMWYfcRpepn2/fSn+jn5zB+arwYGmtegLJDzhdaSIc6g9DNoxvZ7GYgH85mRmw1vJlr0P3wNS+rgIRjgnoY0tii7by74IlUduEYAiVFKl0cLXnFdvJmZAreyYmbW3q1tbkrIzJsWWfdWEaTsjQidNntNYe6pUt9lVBKFFICWGi7ZuAFAxvjC9LXnglLXPZCY92NUStnFPPLKjmB1tubvfaEBZMFEte53VjsQKofJNjRihDFnOPUlsFubxZF3ygY0sp8ekCaF6puagEapK71pkKqbQMKkzF3xvwp4aR/xqgB1i77V6Zox31zF+GxsdLF3eMvS4xbjDMIXVQnzIldWG2eH6zZnRGacCyF/jUnvEqxaNrRUC/8RPxoY1ObWpjbbdcPaxqePwFeYhLSyF5VO7oz7CiWSyJB1ctI5AGftL49exiT7cZlEkAS1bL4q0nSAbSXwi9ScfuPZRk1bGa07BnZL8S9iafE21Es+mwjCfil+a46YU31Izl2KDEoKsobj7rGP5S4rB5GZi1GPwsQ==
    client_secret: AgA0d8nAoGucp75KQ76QS13GsVxDsqgN1WxSkGlQoAmt3altOl8W3/QLl8D2rNREoCa5Iw+IJV4TfRi5I0npwd+LMbgB/+wBnSSP9aXpB/jyeCCuCHod3BDGQo/p33MikUqKuMD+vguIOX9JMRB3cURWeLuVyoOvNHggUYx1gEYSrUBO4JEUaoj6WFdGFlxzCpuULWL2ogZiZwfssC75M05/ThBiE3iW8zI0uP7p6IfTZ4K1JZRxFMT03Yf91NGa+Of56Mnub+Q8HnwdA4drzeW+PAFJ+8jSUBZ+vOb26h8GF5GD5c1pFtIGoopeEPeMEwyLCPiil23lHiPfstBR9G0XT8++DzD1MKwBlTLLCo+ukWjF5wAiUiBQAW8mNTF1n7ZYFhc0CAfpNJEPMSWOv0lzeQaa/HffZPC55sYjRcP+AYRDda/HrMkvEH4ylHm2yGCeiFynDcquy1aUauk7JBP95OIXgN0K3GSDuaZE6tLSrMGjB1394RDJbNeDCFtLTPlIyUPiSWSK1KhmcnEj0AbBCb4KLSbQ1sIhnqK46tZGrafw0VNa/WkObMabDF+dnbs084osLEPDkuz1lZQBTt/LmvSjwB9SSauyXyU0Uza6AcTcdu1F6zetcQXkIp99qRsPQoGAu++B2eWl4R9PcmXc7A88US8y7fIXGAUZM6B+euPRfg5nrHMvbEBbRvZpPfQZ7BiVz1vNw05zQokh4xzlkS9wz8ZYJa1tPweknU5o6T3/iSTvPtsmomny3VBIK+giSwR/x6Ww9QfXkgrMyTo=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
