apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - sealed-secret-backup.yaml
  - timescaledb-statefulset.yaml
  - deployment.yaml
  - dashboard-deployment.yaml
  - service.yaml
  - ingress.yaml
  - backup-cronjob.yaml
