apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: health-hub-api-token
  namespace: health-hub
spec:
  encryptedData:
    API_TOKEN: AgA5OP+nb+KrcgGjdKqgV6vqksRhoTFhE6PQdutaw/w5tOSoRS8cYBxUU3xLGL17+JWEf2ek3cmT2oMTyoeWmTP9PaPIGCr3IEY//5ecBxwl1O7VsQanQWg/cYAjLR1YIRCBe2jLcpUnXjIrpg3T0tRSQuCnYcv4o0mIL9ZWaUEMViqzLhQxrfWPsvJGNkXfwhcwY8eyRc3ivOOeTc/k3fQ+RLJ8M8a3RppOF/l0DLpY2uITaK5TwaiBQ7tKKDKhKh1OFZG+KC/bwDTgv9IxGb/7wjkb5W0hI0hGq081N3A1GFniTIzBPneey/Pr8oO6K65SEfcuYapP26MZBpE0nmJ9YljzjPA5DkBdCVqZ5KnpsuOdadUQmTfzVUXn5z7SCUGAQwB5wocwfFRxstKasr+OTcYdNbEoKipPyOhJUT/O3RXmAT4FIGYTxZUie5brbOpXLZS02m4UF6r+M8rBsKfPZFSHEuMf1ptYcnT5P/T7UV+45RdndCopDNsUtwujCrWb+ccvHGFETzuG16IRA275dXVfwp1uqLWW2AQQBiSqLVG7VhN7t127XqSru4FyEoaaoMm3ECbsYXVVl12SdPNdnnN8PlTYgidCcKmBrPD//fEEdH3Nv8TKPiT7+V9zNiv7uFNAlItCHKjtOrUMTO+haDKKEOvFGxCOKv9zH+bfMaij42fqvHxCRYIYuP5yaM8DvHrbUPX9UpVT3pDLBsMlUuUw+6coHfFLnG/WUd3lNcanUPHeb+Kc2g==
  template:
    metadata:
      name: health-hub-api-token
      namespace: health-hub
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "automation"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "automation"
