---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: health-hub-secret
  namespace: health-hub
spec:
  encryptedData:
    API_TOKEN: AgAv7m6kyXN+8vkDbivGjT6jqXBkYYcFUaDAQiwmbwoZEZ+zpUfAK4v0KGzH346bFz1I23X7JGffj7yIaQIvwynlP2urnDKvZKZNOwJHl1BDDM5MMYa3VzBzb6Vy+TO+tCa5QYe2zkXuykG6Ii9taKpftj2VLDASq9Q7bh+33ZrspzzH9fdfh5WbIavqcarwqU+dmHd3fAHdOpINxLQ9rhIsKshGSFn80sSs/tEwMKSfZ1t1lxYnDN5Hx6r32YJKzaD+mI55Uzf7hCA3+i8PK9GIFgUb9EhtWTZnxEudly7QouPh0LOHls37g3KtERd3aTbsp5F+AV6qwK/ZJWqB9SR1udKHEDsUSwEFTXeFxvHig2FjQck5wqBDBIhKIP+qxpGJ5Z0CjsdXPHtDbIvlDIsHW5bDiLSPfmMFLvnQ4BP97QdyB3XXNq+//Yh43BXtvMBlQEHHvro6golZ17uYbB6Hr39DuJwi3foBXmH9CCRsXvPu0L8WG475ywj0FCnauBVOwoRDwuj7+o7Y3FyMUjeO/d9h54zmJLonezBYVE8Kn7fcGczfbBkpTIaN3f/PbGbojvTeI5O23REnLRxgzfIba73sagVTHvJW4BTowNyPylNBafVzT6rGFeGwAY0tcA/9XHEHCGiuicRO2S/QSdqrG0KT80TK1zKoEkio0e2YkeB0QXvjO5J/fsjoSSjdRIB2M0/Nyiq/Hw20Pvz8cZFFD7OcSwMoIXhfJsl+zZ5vscx/+SnyZ9cRMw==
    DB_PASSWORD: AgCtJJZMllg2McbOP5P4fjO61rvNt7IfFfltdt2TNl0A4Tq7+doesexIL2YsF6OgIg7ajcnkW+U/TLN0YoBibb98/n+IQOROzUXEayQN8jKvqJcyziBgFRCcycgGGfdF/WVTGG2noyGETvLPm8SGYHW4ZJn5jXZo4tU2HpHLhde15tmyhhD+B4P+oQzRK5ZUd/K7oRZfTMJb8XNyeUqPoiuTp4n22mwgoc3UZQzUqGpIMifgDj/vh/vunzLQoJbp/ro4KPyLSEp2qE6g88TRhIgvruzuO9zSBKpqvmNA3LvD8rbhJZdB1+YQvEbJuSYfN7rJ3Fi6/jwEkzIWudQ5XPhV3co1fRGxGwnzaoEEnVg5NVX13nG4dCPJroDbzOXWngcpghT7CN8pYMNbpQEjtYa0jx53tXcGdJ4roYft5LskqvifoOHqiQvYh3H8jXyta+5bHtTfoE2tGB4vXsRuEjmxYzw+54Ti/WMqluBuIGu/JuqZ1KHlM+svxSDFt7twd9gizj9D3inBCNytpJD9vCN7VvorJNxJJlDh2SSUkqFmbc0h0N0BoJ8zclDflm1evKKZjY9BLxPmn1qGGc6f/FN5o/5yhbzYg5FPWsHrEhNxs2zkl9s/BbHlcWRbdZXLjgRbwUCB0zG9/JmvfVR47/o1lCulHgj3jf21HCwFU4nE/7AeW1hhD1GYqL1yiGzelu9j19jNGTkOQBXvWfT+WuGH4+P8Fhitcwar7zac4Q+WVg==
  template:
    metadata:
      name: health-hub-secret
      namespace: health-hub
