---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: health-backup-credentials
  namespace: health-hub
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCD290a3BBXL++7CVQi3S/GrdFg58qLnThibIVk0B7VsQgIGSOXCF+Jf+5UezSXO95kWMTSgI9gorWs3UqKTY2124z1+NdXZU1IBRFkzDq30C3EqUw/InfvRbHtjDBO/qBFN0opohiv2uY+SG1Ra7VF5i0t9e0BVyAd8/VzMM1PqAiov6rnuq1qnwD5Y+s3YBC8Ivxqv9JNnyXcQGwQ5b6KQxa3+VDR2N8FXZRfLAtITjXVfjus5JEj+mvXSR+zxVjWO9vmzCaJZtuK9wRET2em9tbVkaRaNcajDkjbIIcra+VnHodRNHGyc+Vu3LTBwfpC+hKAyRKX/rM0H1k8V8ZYLfXabOz2jgiU8M81fC+MpLJBiEowwc8iqIQuZWyQOpJEPd1ieur5Tv4qTDNFF4S9foXce5ZFP6t1cCnOQu0AkQV+drdHrJLxLfo2cd0y73iLw8qK0ntqeKxCz/EUKAcNw4BTnIijAwBoHab9tq+jv0D7NXWDXqBKdHzKdynYpXUsmggtA3H/7xSv1nofukZZLBUMFDW3yd74qAyCG+7J4Q79njIWSrmGXeJPJKJxBTpBslRc9sRAhBCwSG7tDNabWckbgcm+pVxDOyLzwJkaLxq7ZwgZzwCZDayHiWaE/96tnYkxssdBZ/djgFjNDgj+wXGolAWZ9dyVll3PqQ1JTcPh452wZQAETMKDRljA6rJjbOv5NReSzA0tFp0mSzvkKX7IxA==
    AWS_SECRET_ACCESS_KEY: AgAEFGyTNtscYQRgeaYBruspCuddAELTPfQ6YfcLzZ1KE2wV2hmy/oSvPTGSh6qvoABvz+sqSl335bXhBnnBeosdu6+gb/WdUSvla5pc0xWKCbfFRHzanFj8DKJfcvvw09LyZZVCLX2BsKoBF58oxSrVb3K6aosyWzTajDlecKPiX3bRvErLz7Ix5Ch8ddK6feTRwDuTU3G/5FL4KJoEvg2ZkdzWXp6vqqWUGVEUSlXrm8Ww6R6eclUhb5FUnEIUZbVMt598RZlYbcd3uIlYRJz/GWs57km15El1q4FrBPu0N6kzXfY9W1SglyhYXNxwatPkzL3wN6dsErcitq6W6Nev7ejfxIC/QQYVTfw68dCWUexEnvV+HhkhMcZW6RYW5YhQNH9VW+D+C07fK/utvpVU/50IwH8feDxwTcQe8lFQGV3KgjKvjXhcTc4EdEHNScjB1i6J6PegBVf6k4Vv2Gg3tnscW/XKk4zlGK7lS63MCJON6jDwMHuT681c7DL0ThSxv1xs9QvSWSXxG2jSPwHKMcFmKyZpOSSVmgDOv1rGzBoXPejAtvP1g/OBHWurKDOrSt5uCx3i8E5zt5RHehzvDRHwwUoaMXAaCvON3bAC0/mtQK7tpbmm9XnWw2O7+SxpBDCg/CZsOqtrMNktTNkSvV0WmYiI75DPkFb1LAffb0UUzE75s1pwZlw8hENshV8AFbCljaodTbFQfccPQrAY9Dmnoae0/bghGPldwD/13gW6PxfQHDtO
  template:
    metadata:
      name: health-backup-credentials
      namespace: health-hub
