apiVersion: v1
kind: Service
metadata:
  name: health-hub
  namespace: health-hub
spec:
  selector:
    app: health-hub
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 8081
      targetPort: mcp
      name: mcp
