---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: saemate
spec:
  encryptedData:
    config.env: AgCEIomAvkGoVTl21cBPs/aOdJ2GlGWSJMPTEzLh8zd9fFApORvBIeypx/Wlb2IYnW3tDwaMvwo8YY35eHGGbOYkYwTuDouF/aZjylcyokfvLOSKsLq4SJI7hnlo0q9vhIUvUdYn+9nwVUBZNISHr/WfWtW4QeIWfzi91gp0QXEMT95S0N1it4A3hkCYHSmXwc78FACVSvdMdca8YGMnqbT0XEmTl/Rp8j5qpUtdP079u+hP1G9p2m5UOSBX43Oe5XmuhGwlb5ttI+v8zGnr/6KqzjTAgxkVhNsmD8gY7pDXNarrFM9phV1q1A/Kt1A8HhdWbB/mi8PRg/xf42tlf1RAbgXADakes4DLAeTRWDutCIEmFEKExcH94l6Ug+nNVzghfDcunM7/d539VYyP6/iSpXrISKwhkkWBDImAzuJfQmVBv72GAGLlDEhCDZgJgCykua+39DIDK55yF58YyKmvmiT//cv0FzeXNdulw6uZftMHXSOx2CrVJmv9kUw7uocRDG1xO9rbTKu8YcGBt6rebGGqVhc9gYGzGZMuKmdT7/3hqiGwY0IsX/M7kTpDXoDKiOejSwU7JlmVYCMVA+5F0anwLxAlAxV/yLYsqt942lP7DzwOnmcNQi1ddRLCf+0mLXsEySqrXUPNY8wbz+orM0GjbXI/7g0M85adlWmp4PlI7r0n5XeUA7chg7KuvWLk2hjRjkeH996YbSUcyPsMw1rbinCxkxLop/gELuRIMyFeLGl9YQMibkLQR6G2Qm3MOED7mDCMynJFI0i/1/u2xDRdJ/KA7GuosYg+FaXVplRLAG8TjcA=
  template:
    metadata:
      name: minio-config
      namespace: saemate
