---
# Health Hub TimescaleDB 접속 비밀번호를 SealedSecret으로 관리
# 생성 방법 (비번 로테이션 시):
#   echo -n "<새비밀번호>" | kubeseal \
#     --raw \
#     --from-file=/dev/stdin \
#     --namespace observability \
#     --name grafana-pg-passwords \
#     --cert <(kubeseal --fetch-cert --controller-namespace kube-system) \
#     --scope strict
# 위 명령 출력값을 아래 encryptedData.PG_HEALTHHUB_PASSWORD에 붙여넣은 뒤 커밋.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-pg-passwords
  namespace: observability
spec:
  encryptedData:
    PG_HEALTHHUB_PASSWORD: AgBGYUQA8eXVWT1zL2Za6Q/fXH1cWcvPeO5vsPBeaseLX6GGRfjqbihRDmmb7ZMkONNUJbNeCJiQUbRQZtMR7b/X02aENZ5RYhfJ+9ODDwfpFyN4sem3C1kF2AXvIE3vIyjughwplpKFg5OEn2llUQIJ94pLhsLapD+TpYYALz06tqJcMKHCun3HFLV4cw8gjdc0YUAtftqx/kAd9XpWd2urAfDjXn5SQpGsRHNLqrs4JLai0tNn4xtMjDEnskvwFgt5fduuc+9KJ/ocUsxXfvg1lEd7bkzl0FyxkMRY8clLl973Zhu4zcVXnzeun7heNLZML0N2JRLR3kngodi+QY0D6b3I6n4tnq9MMx2ak5OXGapyOu+ayELX/95STGcKICv5l4xOkt2k4pTJJoLvG7Kg1HWFos/WhVjmfWGuhKboa1UVCRpj7mzJrDFxqfIOzCaztzqeRwnEyRbOqPVgg5eM2IQtiHENM4Si3PD826h/Nv/A8ZlDYHSoW7KFghaWcut8CizDNk5KdWE/F3EwCPM+WoD3dx7ztSGFp2mgjlJnf1rC3JmuDqfkEFRKMie4Zq4OkxUj+GN1PZXy0ENnmaEblcdiaKuoygg1ib2cskw/hiq22+O1Hj8U33nd+w7v5Vqq7Wl/TxJDmjF8hJN3vAbtUe8/yK8ed40zqvIm+bMpxXI3MrUBAg8xt66MIFKvfvunl7YufFPCw95BHHgF1fppJTUQ6IlWw5F8QTGsaRySDg==
    PG_LOOP_PASSWORD: AgBoQ5lidvdsk9XGtwoqI3uXhPzFzz6sPx+UIANb5IWzzVA/7bRuvLPSx8xU/6ZvB+Rv+es88VOgLfqIV7tgI7adbr+ONvstwD7JWZ9RYzZk2tyENm24WTMAaNOnZnkw8toGoNHkwtpJcLrSy2n+4RVGJM6ordFpHeYqCag6SwqWZaJRCpzeCKtSiG2rlazU5vE8nNF55LvOkeBWePSXIuXXj387WBJOdbOGvtLXb6LhpRa4taxp29rSuFny3b4QH+hC7S8giTg8c6c5wQnqpg7Hf0Iwq5fWOmfaEMtJ4G/KOp9zc5mw8grr0pgyfmZZrE+oXGv/hNbCwqCI3XB+FY5qJyL6fmCW+MAIPsQvJNdddZSBd6W2sryzTGYL3FLfFAuEOcYk5BVcsuOMrIJecq6rfuCh1b7FXDHybNDLOQwsOE72sg8e2M1aWLwglKvHHflj6mT4kCG4Vz3OV8piWa51GJeXkzTCruJwSgHWf9ag31tf3c3+LydYTgHLWWw+sTUKFSO9Sl/bHGM9/CMsY4NiaPib6ihqJpJMn8ez+5oyLB+h4sMHGMUK3jO0838F0dchDqeFnNEpfHDTrOAvw9tpckXeKIoCFB8BsjMQr5t1GTnbPK6EZByqgt+z6W0d9S65FDfNmSSNuZEyM/ZDpNH3Mk0DiHBloKwWLqJrHrj7pOeejIxYKHu1qSOFfQBa1cTOQVsGeQyvobxbMr8bT09jQo9JPhGq8uUZqKLLz3ZGqQ/u0KPLJHzcUj5Rxy86fW0=
  template:
    metadata:
      name: grafana-pg-passwords
      namespace: observability
