---
# Health Hub TimescaleDB 접속 비밀번호를 SealedSecret으로 관리
# 생성 방법 (비번 로테이션 시):
#   echo -n "<새비밀번호>" | kubeseal \
#     --raw \
#     --from-file=/dev/stdin \
#     --namespace observability \
#     --name grafana-pg-passwords \
#     --cert <(kubeseal --fetch-cert --controller-namespace kube-system) \
#     --scope strict
# 위 명령 출력값을 아래 encryptedData.PG_HEALTHHUB_PASSWORD에 붙여넣은 뒤 커밋.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-pg-passwords
  namespace: observability
spec:
  encryptedData:
    PG_HEALTHHUB_PASSWORD: AgANRL4HeERxKYidbLgLDIs9yZ1P9LjY+2721Z3T+maNHytTNF0jiEqeWPnQAE/Z+8mefoGu9C3k+R+Z9ysxNQC8BogduyVjQ0apfRs69U3HUcLGnMuTY0goXx7fSSBsUKEDQsvnciO33Qh39NpJVz59KzpVrCheiUL1cXptEQelTHGceBwiMWShxzDaeKfXcuSLQRmzzlNn7sOfLeyzDUCNyuz1O7PfoBXWzb2uuaDTKCvyJA3jav6VQ8cMUIQfdyj3IAvLoRnipfgYhVzEz8nkbbuh7yxEn1DcLRwYvtqt1772c+sP6e7OV3BV+u+SoI9g52VOdDeRPYGoJVZxoz2uwoYJRmLQbemGnBJ0KuJXoXbD8+cG3f8Bz2OzYL64cCWY9JDwJ5qvL8SVBXwRnu4iKaDBDVrNlAa/C8DbbYInj4WHYcyuUHFDLtfWS5RVSBDUV5gRSUH8pwcXwGZPv2HQmNRYVU72aoOW/9wYXwiALeH1naYUsfA9qSWyqyCAvSVsmNVDy5mRvjPouMfXoJhw7rQ6SwMlrz41ZaFNUSV4dsQZZbaI5Wq5NlhCeSZlj4PK4zzk95QbrcTsXFBOqXbOFwGwHXqH6LNjHZDl9KOKkncoN2V3/nk1DzyxCWBwgPA/37GROJI+YAFiZXfQ6ZsRXjH/FDXjwxCzzEYAA2b9Fgvk0Y+gl6Y9e688htCRgUebizXt5baGSd3/4JPaCBJ4q7TmB6k0AwruzSTx3kqMig==
  template:
    metadata:
      name: grafana-pg-passwords
      namespace: observability
