apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: seafile
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seafile-mariadb
  template:
    metadata:
      labels:
        app: seafile-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              value: seafile
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEAFILE_MYSQL_DB_PASSWORD
            - name: MYSQL_LOG_CONSOLE
              value: "true"
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: seafile
spec:
  selector:
    app: seafile-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
