apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-hdd
  hostPath:
    path: /mnt/data/seafile-data
  claimRef:
    name: seafile-data
    namespace: seafile
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - json-server-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-hdd
  resources:
    requests:
      storage: 100Gi
  volumeName: seafile-data
