---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: essentia
spec:
  encryptedData:
    config.env: AgBE26jHlVc/IqE9RfOyFLnngrjMhcyRYzBUF6g+cX8DUd2foc+8TB0tjapmf2abuZstt5U08LWJGs3xUR7s+Yw00PzGTOZ/j3KGvFPtlJcOBwqLRwD3euGnORZHDZkBtNbOi6YGBAhgGtwYkMmEpq+EzeDP6aboyzPYSkYtH/EL6907Vqlbl8e6xy45X6N/nCANWieZJi9NJ0SDJmf0EcKl6yhzpk3J293mgsblovZN0rSqq4pPUh4WdNqwG5x8lWGVtzYiGt8DzbOs8hYnrxhBcip7WjY3u9UY+8RU6D54vA/YVzWjgt2Y8E/aHnaAJTwzka/6gli9sXzWhBDgj8+9k8vfCKeCbxT5Dua57MfruxZ365CZ4034s7StjwJxv/sS9wJALIcWgZ/1y2x1VUDWRmhN4s3Dx8jl25g/beKFf4LjNBkIRjR+d2FMK+7M6V+twv+HfqF0tsjoMLzbkA5M4GRZmOcsGYo1bYriDk84WPUiVYzvwLBLnYEE37M/JPKuj9MpOTTDBY1uI6N22brnKnSvpFxQu3917I7Tjihb2iX0trkVfX1sp4MVxY+H44GmMdPxNqkXHpXpuLab+QfK7Ce5tMRBz1fGAudwmg9WVnWtMWWhhQfrt/yrjngcgwNaVXtFe5ec31T9Ob+bqzTvRTQ3qkWJF3nEe7XQ3jVW/e/tJ5yY27wCqbYnRDiLIZd83fiajfU7po2Y8dep1tuwVcVpdU/uwm1sWNqNZ+Bj4Ui0s3phXIu8gTLclRKF0Togm6c2jGue0kBMFFJKSvv1BYyx5BMRmP+pryYRHAtwlNWt3Om9Jg==
  template:
    metadata:
      name: minio-config
      namespace: essentia
    type: Opaque
