apiVersion: v1
kind: Service
metadata:
  name: otel-collector-syslog-lan
  namespace: observability
spec:
  type: LoadBalancer
  ports:
    - name: syslog
      port: 5514
      targetPort: 5514
      protocol: UDP
  selector:
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/name: opentelemetry-collector
