apiVersion: v1
kind: ConfigMap
metadata:
  name: go2rtc-config
  namespace: frigate
data:
  go2rtc.yaml: |
    streams:
      webcam:
        - exec:ffmpeg -f v4l2 -video_size 640x480 -framerate 10 -i /dev/video0 -c:v libx264 -preset ultrafast -tune zerolatency -g 20 -f rtsp {output}
