apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media-hdd
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hdd-seagate-1t/frigate-media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - json-server-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-hdd
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: frigate-media-hdd
