apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: amang-homepage
  generators:
    - list:
        elements:
          - env: production
            branch: main
          - env: staging
            branch: main
  template:
    metadata:
      name: amang-db-{{env}}
      namespace: argocd
    spec:
      project: amang-homepage
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          chart: postgresql
          helm:
            releaseName: postgresql
            valueFiles:
              - $amang/infra/k8s/db/values.yaml
        - repoURL: https://github.com/skku-amang/main
          targetRevision: '{{.branch}}'
          ref: amang
      destination:
        server: https://kubernetes.default.svc
        namespace: amang-db-{{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground