apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: amang-db
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - env: production
          - env: staging
  template:
    metadata:
      name: amang-db-{{env}}
      namespace: argocd
    spec:
      project: amang-homepage
      source:
        repoURL: https://github.com/skku-amang/main
        targetRevision: main
        path: helm/db
      destination:
        server: https://kubernetes.default.svc
        namespace: amang-db-{{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground