apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: amang-homepage
  generators:
    - list:
        elements:
          - env: production
            branch: main
          - env: staging
            branch: main
  template:
    metadata:
      name: web-{{env}}
      namespace: argocd
    spec:
      destination:
        namespace: web-{{env}}
        server: https://kubernetes.default.svc
      source:
        path: infra/k8s/web
        repoURL: https://github.com/skku-amang/main
        targetRevision: "{{.branch}}"
        directory:
          recurse: false
      project: amang-homepage
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground