---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-s3-credentials
  namespace: amang-api-staging
spec:
  encryptedData:
    S3_ACCESS_KEY: AgAkUVm4x0Y47TiQLnPz4UjGA5fyo4WDjNlvPzHlcA6k1/ZzXij0Tmj8BCng3Pg+vyTi6TRa1/NUdoG4AELwvXiFny/n4AQB0vHeUnarmzVmCUr1PWO+9f5Y5vZQZ5MdUyIgVntWWUNRjHw948XXARCAjkEYHzatnPtYkRvgN5HwkJ6FN7ZTxR3qRJhANXQ+pEuHF/7POUk1B2CT+b6ASoVZhWxh/ua4No8eqFDpM5zOohRmbt8+Q2pYLc9W1IS6N4I5BQMtgGogqJr0ysT9N+PN3rZ5zvmg55yunfZiAt2YE4LI1X2uwdcfvWnp4ACI1jHvHa6ZUNLDXZP8zeCE4xzC3U8WUbodEwy5k2JzjgLlS8oFpRmGwrvopL60oBQEhf/2zyYWwE0OfiCS4VKwnARV5V/zJWoPwkas0SGLlk+/SCqSOrb/AzCJEIyhKLhuTE4l0SAyXmRzGX12MDb6ewvztQzwI8et8L2VeRnmG571Nu/TW/LeGbG8gMJ27gY59a0CmKM0M69AGtF9SrDBtD49xbjkR64e1MGKfeF4TnEz0NxFPOIwADbVytbE5zfSGzByrXkJRA5fgGb9X0L/qjmsYBlLqPflyr8rudX8EXr7rI5FBxCk/HaCpHL6Ee5eNzHNYSmw2h09Nzz/u0weyk+Ch0BYXTicwYqliZcdmYF4YtWslXu+5Z/EykizL4YwMVt0yXZIDP3npQgIZMeMWGft
    S3_SECRET_KEY: AgBEIOUPRsN6N5O5h/WdqKWxU5lELclpiqqBopjYent83INbxJnl5TR8jtairZd3SNlcHFigajdrTSA+j4cLteEvaDXwktqCv0fu2kzZ+Zjpi7o4SMLnxDpZUhPHePAIsxAeK2hWSZUFulJJlQwpyi+HaX8phiphxe4aD5Jf0BiFukY4dLGo3HseZUKjO0kA/SvygsgveHU66cjySOnil1BOvXvdi1z902BCsEUglAGGXzjFbk7zKX/782n7bjFl0GojBM6+XcbRt4urgAmWuHGiDMaIWYRjpbKNOH38Dl8anZ0YKsOxDMeO4QQ/KcCjLCICx2A2E05vExTmq/MZLGBIhF9xWwdiLH40RdEmCRiha3dHVptuZEgY1upRkmJbkIlW4tejopf6Qhx1Chu+eEoasfqDRZj0d7tQ+iOVxEAUDX1Db2nzwTb873vdPN6KVskTaQ7VkmpIH7c4gnrDboZyAAwfumwmG+N1+aDomDwnMtPIAe1mggRc69AYyxbKSXYMZ6Qg+MIGUgihyNnyG+cxZG9T2ChfHChv+U3iWAIjHBlAMFfRM2WQRslOa9hrz7df8DLwZpRZ1oMqOyMm2PhaKBvgfFJqk4sOD76xTAWSuFeYSCKNBEIWA+BNfRoknIWIfONpJpQEXTDSxggAEIYgmeQljnq0oQHnMa2V/h1imJxQDfj7TQz2qPiElMk0HmWMAlDPIN8taoczPjHkCmbX+qNxjarGN6wTF7quAuJovg==
  template:
    metadata:
      name: minio-s3-credentials
      namespace: amang-api-staging
