---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: amang-api-staging
spec:
  encryptedData:
    config.env: AgAJAvbfhmmwcUgGrwdTnbFYeMySwF8BDH4QzBbFGLLC4GCGSqr+u2oKcVRK7krUPXyJph6fONJgYLDNg4CG1WlJgcxx4im8Pc8NBljq6paeT330wMqeXZ7nI0af1ByyieW69AvoxEEwz6nbv20p14WITVwXpU2IDg9iy8vicKlngEask+n3qMcpbn+/b728U0BrOQoM6ouulEatgoBJa2uGz4DgOI9F4T+NDYUNs+MWfZEB/swfILhzKx06bqktUXrN7K+gro44fYkubTwNztFAYVrD4yqbx375a2CUTRK1i2ZhGqE6QMNZNaPG4PQaAxRXZnnW3itXzFrzjYhbbd2P+7Q5pJv5Nnf2F8twDXOqZJWCxBY31OlZb9q/fKuCOANzaW3+IB86bbhUdleHoS2mjZp+1Df9nsJK0C3DvHqWyvaQ+4gy1d01EeZCodtybsV3YSwCblAFdQkCn7pAu9WySboLpT/apxNPd9AjBay93QjWU9tP59OpZfT5v2anht4LNpeFIYteJNDN5KFIbYmTFhpVCZmsgNGW5bNBL5vT2KYzEbRAQwP3tGdc8jU/xjT2hFBOUKM3vLwAar03Z74LE79TnhMkr9aZUOqqN7GEahyoulZynDU3J30q6BUzR22DHkrFJYKHvy6jsty5cQqy0Cm7rrcbBuHL1NE64Mmy2ipXYxkAV942yA9usmogAVIZpBuP3uJBqJFo0Vs83accRuS+4vOHpIsbALjEfCLAlIyrpoiUduQgWm/JprGJj4hxQ3CktgPAbwA5RhEPHLQQHGjWTqBrIRo0VF7X2btgiYWnJYx3IDr7lQz682czkYL1aJo=
  template:
    metadata:
      name: minio-config
      namespace: amang-api-staging
