---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-config
  namespace: amang-api-staging
spec:
  encryptedData:
    config.env: AgDBznjmWAYZ7jxb+iepwuU85l3cJr4qTa8NYBjcynl67F1EXp8t67Kwt5BZ7dXSHLbkQTssj4lBqlrM2h1QyIM6lE1bSX/qLoSsHQACyI7pj7AU0oINxXacfGL00uQGzPrLPDtaR/XvsVr4XNF0UkDq7Lor/SuR3s8rgftdpSgFAE4nk4cNE37gjI9PHbcSCowDLsw9krGbizgBKsuEe5np7Q2p2O2VwyVqbsozm7mJCUXsc+MXAVeh8JWeO8QRnxMFVQH8SMMwUsu4W/9599TbGIIOP4DOyBJZV5Ofv+WN7XAVP414Nh7bvTY3QhvpblUvX8nnlfvnStmaoWrDf327wrVi6BzQXAE6217H8TYPkJcY4kBKA7Nv6J5PpMnS8GESlsnnlDv7gk27/Xh929qpK9xgDE2xyLlVuNJDnO4oZI4slQ1yf19S7pzK7gRFDIB1/JQWKMDi36vlqq45V6vBKQpVwInDA0Q5BP5il3AyXlJMy4fbKirxTKhGfhTyJKTBPOMcG/MvUA1l9ncol2r25N60BByN82jLCbDjXrqs23nenLsDqBL6xqaw0xZx+ui4m3fDdf3j5Yv5Kmc2tdJimuzwkSYMT/k6e2bP3UsI6CKVpvYCCSv4yIK8KUQJWOjoS+jh8jqVeFwtZ3dgoypelOHYFjuUZaJjqrtxWvQxEorxY4jHtH4RRf5oPgR5N8tqIAUVHQVwHtQLWy24QZkT18DvRNZ6Ag1wr0rcQCysS2P5un53siAfhDU9aNOz4RMh/hoqGbGqlm0N5mJWOURuxfx+bRaqOZFMQCwaSBQkVDTWLphBD+xuRUCdg4xQeutwo+0=
  template:
    metadata:
      name: minio-config
      namespace: amang-api-staging
