---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-s3-credentials
  namespace: amang-api-staging
spec:
  encryptedData:
    S3_ACCESS_KEY: AgAARUJGIkdbYkGkYz03nLb0L4arFfFZtfRV2ECXsCQ0tkyPHvvp65O/mAka24ZC2p+HZ++RXBqsEfhDWgPxgW6JC7BS95kID4g0eXb/Y9y5oiZnTMQBrQu8Qadkhd4+nsVCQpc3+9YfufLWaTuoxP6c4MVLGkPXE/aOV70WagGwXMQRS1wd2hlIeSsfWeWxNHmqv+Q6UD7ZXRSZUvuX0ufDam6e1ImjZsS9vFI21XJe3O3N1TCOmDlGUcjWo+h47MdMz2R8a4v4amvD7WiX7Fi9LY03ZeVCiH0Sx54hREANJN7RN+oINX9/hRI7Ho5T6ErueJsU9lGk/HirzII3gbsBvbdL4YuMTmbGFMmgP34ZbtQdKw2w5w1SA12i32sgcTf0twwhNeg6pJPfZCF28sbpuWNrcyPtVn/PtN33V3JHSMzxA4KSWFbp3exVMOz1N73hb4fPw5PmZTohyX0jY67Vr11mluaNc7ap/oJtb2mgcdU4Dlu/qfh0S670pxMOiYvI2wqV1J8AboQyoNXu6ggH01wDws1yqdjEoIyrecxeLi1FUlkN0BVIvxQ58zw8/6FRutEE42Ob+vMd0R7cvRGxH2gaZCZX+T0laLL+df/5SQi72s8+n/RPHYS5T6hGUgev6W5cO1MfBr1NzT8140Men0a8C7KLZFXNisrUOzGE1vglJGRBSwiLxtEMBwcum+KbRcLP/IuyJuShzPH8CsVR
    S3_SECRET_KEY: AgCNMigH39bjDD13m7ZlKKHnQ8iYoKyqzreTOcTQrasFXk9bhu0m1q7029gzCtciEourYfazbEekazE+1BPyLdb7GX1f4zqBTri55NotogkKrMDd/Ja/2+z5SlAVU3pKh2R5GNVfExNg8hWwX9gFlGCNhHih7a90Mk8EEyHf/A+51qNt94dlDsL8mAAnahRM3J88xGw2CWMd7ipnFs1roUzZLL+UGM/ELOuit9quAb3VrQXbpL5RqJ4DFppLZhV3tVebeP2s2e5RQf4MGmqDglONRkMg6bdxGuxIEgaQIUj8VP5UAZy0+Rh4S+Ot3T9hJeG0bUScvRqoQ3KqFky2zRSwGGBTAqDALAUK2aLs7zKmoMrUT5UnB4MO3oA6HmVojAQBAp1VqsdlEpObESJZ7gN1/C9nrsMOxDk3cpHs1/1WyEDKrIo0nqZboH8H1oprPpkT8UeABDwNdqnDRe6Ks5T7L7B+pPXlAUN3og57sAUzXCxf5Bv3k1VdnyaCfNnXyWKBYrM4/yTM4xtziMIfakWwWgWTeGv9gSIhvHT5ZaKze839Mzu5wdqLvW28mThYbUuHVQIo5P2Hvdm6dHDmJ0gfTJW6IOi6dPdg8RRnkOiFPs8yfaq0kGrmYs4Y0kb0LUdOPeIBwwEK/qr0AxoFMO0JlbnW8d3lw0ba6jwQ8/VcsNMTgu8YjyXEb6hF3n+YmJNhrF09/p1HSvDb3u/KrfHSinuMoaiDnz/TmRej/mnvYA==
  template:
    metadata:
      name: minio-s3-credentials
      namespace: amang-api-staging
