apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amang-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: amang-api
    server: https://kubernetes.default.svc
  source:
    path: helm/api
    repoURL: https://github.com/skku-amang/main
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/skku-amang/api
        - name: image.tag
          value: latest
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
