apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amang-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/skku-amang/main
    targetRevision: main
    path: helm/db
  destination:
    server: https://kubernetes.default.svc
    namespace: amang-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true