apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: amang-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - env: production
          - env: staging
  template:
    metadata:
      name: amang-web-{{env}}
      namespace: argocd
    spec:
      destination:
        namespace: amang-web-{{env}}
        server: https://kubernetes.default.svc
      source:
        path: helm/web
        repoURL: https://github.com/skku-amang/main
        targetRevision: main
        helm:
          valueFiles:
            - values-{{env}}.yaml
          parameters:
            - name: image.repository
              value: ghcr.io/skku-amang/web
            - name: image.tag
              value: latest
      project: amang
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground