server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.json-server.win

configs:
  params:
    server.insecure: true
  repositories:
    homelab:
      url: https://github.com/manamana32321/homelab
      type: git

rbac:
  create: true
  policy.default: role:readonly
