apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brain-agent-tokens
  namespace: automation
spec:
  template:
    metadata:
      name: brain-agent-tokens
      namespace: automation
    type: Opaque
  encryptedData:
    # OPENAI_API_KEY moved to shared-secrets/llm-api-keys (Reflected here).
    TELEGRAM_USER_ID: AgCDfmnkecEPKLfJ/mRjOSSVkEcwKgohLYDuJP4ENRn9DypvJNXERez9/6jYSeoJnuMpRBhaQUg9A0A7fbscceWKAI+sJrh00MNU46QeRQxdnc5r7HYyWwvO6WG4iyxxXPWwnds9lvurd5R2MDG57EAPWPLFqqRO8NCgKNSmubfgs53EREDybSwURJskGekN8Tv707wEP1TAghvj6a7jD07bQc782OBVEfYqW2J7/R1DQR4awXKSB7BoNuRDPCPeIRjuiz2GWOoNVctA+9fiKNmQkXTUaFb1aDhBfE2VSrjshL6VyANA5I/yTHIl3ysLN4VqdaE53a3usHp25awpf+6/qdYbjIFG+BmG1Xx+JIEueIpWlqh5X6vAwaUokM4dc6DG5FhzI8ETrGH9e73Am1bJvNswsHDeSVQwGTbaeIhNSNZnxFjvmNCLB1v6fUl6nfzyuIoUTcwo7H7MmVcSxI3wwFfzZlKA70IOr8rJ50C3YdkMgtUk+EfdsjUhVk2CRpNlQ34+DfDsmaBG627Cusp7IxsOIUKueF72Sr3x/wL1cxLNK7/GyIzmqtV3jMJEbZQNWLZ1YgCELI/yrQwJ7pJfxeHAAqk4w9a3Qt4g3IHWYtcXCQG2JzdhcYZoGztJLviZSnWEBtJ6v6GStCasBfECWXRHLtjAdzloLa1GDV/b5shC6yVmt1uGVR+IU6JVaBGwlNLYcZoxVsk2
    WEBHOOK_SECRET: AgBjxNrueA6wESEpMdju+Glvnxg8fy+J8jC+jIg3gEaA4y6/n4lY/GkXYwWhkLiLl+Au35xFV8P6c9Do5tS2uyH2lxjCQCDLdb8BoWaCypSwnv32hFwOTrpgVFPbvgEYmAblCpYMCunOeUX0zkWMyjRDsdrtMQ/SDTRS04mf298Xst6DLY/xegs4cLVy54EUKyNjca80T6LGdAPTpJ05DQ39loTF74UZO9UHcvUE14ow6BSPNq1X150CBcsP/Jf5hk6BHDOw91x82XKOJ5EbNo6k8OLwV8b+WTEnKtnXxCDrkmet5Y0ilJ6KdF+1EIKpAg3GlBziATZ98MJvgB+MDWzHM+AhbHk0Zzal9hwMVFa9D52AdMlThfLdZitE3rpZ2MguX8nWRsAXzWHWrX4VG6dZNthYGBTmf9Mpe5Q6oSvz7J1tkFd3WqZlLYOSgV2IsDZn9ptMSCmudgLWFdQGOiicTm7Fu2olBno3kRdJ4Em3rYCV1HOvC47icN1yiXg9xrL4fVYulAWxDoEFf5HoEKdyhmO7mD8KbRfQEbSjvHR5eOwc6uT0Wm+/I2EAx2qbFpOiAna5SF+DFqGefEHiQirnl92UuPlHtkzHai3GCsOzT0bWUPn0RVefJrjMbhYueGqhI8JxSt6U/ALkfZjRfy8GhHD2GKcY6wvr7AeShKx4VX2BWsA/+N3l/t8Ebs9Sgn4BGcHzxcB/61m7J2T4juX4m0naOHS1jt9jFSGWadlQiuREcAjYZqyq99GAjFApyKqCM7Oof1nzLwv3S/6FrjlX
