apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: canvas-credentials
  namespace: essentia
spec:
  encryptedData:
    CANVAS_ACCESS_TOKEN: AgBH6df4gupgnG5WvWhRQj2BeMzILz2qTS12hzxI2YuKvQEIF+qQ9GTFsWnc62OrB2ziqSSY0LDhO/lLn2FG57xyJLrgzz+Dv76LCKUU8u01E9/v1ROb+M+IB/Y0qEkD13A9Nb5DUA5AKCQYmBcm5qpQ5xmDONHR0zLiXg5e6lVcl8jjTpVVV0yoPlIO/DfvA3jvMX6ev2uL+UsN8CdmGZMVCpp9SOth6fNSkW/2EyAqpftkdQrwbniwC98J0bLnaZmaz70M2VTYkJF534PoNugHdE0WS7xcwTgDX9xyLO9iVIrGxk2qpFWm4HYqQLS5uqfV9FPuxohHSzEWcBgCU8UQSfOpvh0DA9AALv8GrGparzCZ/a2BFnEaExCfwgRIo8lZXFR2xxBhL6knoE7RvwZ5aoStrQGUXAIUQg7hmdDklN2ap4XSuBakHbiWTxa0fKOvlPObzBBe4lLCZNxxcoZ4r0XnmHZKT9kGLKjhf7XfM8xsXed270lkq1DHDEGeh6WJ/lR4GL+ZdBLgSfHYfWQZ/mvM2AGrkda4V2pMj9b/SsfvSadTmvRon5+hJ13uvv39sYPb9ndoJH9MPaBmUsluqfzTmWC8FDG50gBhBHlWuBup3fbybvjRiEFtCysuEBVFSOxFnuVpYhItUoW1TbkbhbTKz6sW9jiKia+wPyJPRgyQuQmS7BiEe3nA8X17j0EaYCisUTXQRF66N0abW7LUFgLnVYXV4gAW8/JxwolUrVHjr+4U10P5pYwSRAp5bp36xUZVqX6tclsKsUmWJ6ao
  template:
    metadata:
      name: canvas-credentials
      namespace: essentia
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "automation"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "automation"
