---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-essentia
  namespace: essentia
spec:
  encryptedData:
    .dockerconfigjson: AgCaHt6Wgx4e3SLFeuurHzpSR+yFYK61d3+X26PhdF47NnqvjCrJOFcgieeD2xSGk8JPbF8y2qxLePL3vHOlZ44G//l7GaK1b3bWh7aumgYhJJEZyI3XGrTYkA34r/HkjXm1uGI3KZJj5NyY3qtu5yqumjwopbDtj/9le3RLZ1rcTVYCbUk3A3z3IVkCSRFtv8YB9jJOFz2pFrWekxlZ3i7LcrMACiHvJVd04ccSORbz4KyMw7heFrkwl2aGXavG8mMQzFGHNPSOHaXafGPDQ6BGyQ9MePpfTiUtnxuAvzqeFIiSuPOkdluT5ypLpogeB5zvNZ9DEk25ZS5vKGqTFeSkRXFM8G77psfj6A3E3imPhd3QvmgSwuAgHewQuEiGkavu28yoLP/ryQ/5llMaJuW1jBw0LaUzM2Fg0oVeeOjdznqorlBdmVycFoyiuMIqMuOXiHiORViUdabJbL65a6GZYwL9fkigzt/0GbeMbWDNmgRyG4Ab93XTDvAiI1AIQCcukp2PrDgRkufjYC1DZlcgetltIo0yX4Nzm4ttSYA8RIFEPNLeXMCu9gLuO9lOslEc0Sk1ODvsdF6eMjfCfIkQ5z8hXfweSsgdcORdaAlSAH/kOjnDBbbkCw2VryLp6pK+vy25I8/esI1L8GsSt+Wm6BZ1/Dbdjt0B9CjLPmShNgAWYoiNhdIKWCWSJho0dw6vd3CXwLFkV0w9MGUXPwhq8lgbK/CLXG6C5rpPDz/9alBc/T1E14JWa6jaRrUOdY7J28rb5kKNuHO1bje3df4lNc4/HDBe5JGvKS/7TtkyWnbS3lz6WmfKCdcfbOs6Ea3SsNOgOmn1QDAJConzd/niCgoknTWr1wE+hSHOZeEDu26j/fByz6TYDv//UVmGz9Ge+n8/5kTbwe3l2nho7ZYKUWKJMSp3ntIJtU5ISyctrgSVPgPkQ64ds6HF7nvbmPpEJtg=
  template:
    metadata:
      name: ghcr-essentia
      namespace: essentia
    type: kubernetes.io/dockerconfigjson
