---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-essentia
  namespace: essentia
spec:
  encryptedData:
    .dockerconfigjson: AgCODnd7EHlOAAFXcyqImA7+DzQvPwUAN4zQOa/x9/a2yoPza0rNR37R35V0XOy3XcqGEeDZJmVFvo4iBSWKV/WyaNqyB2zjG3/GTI+2TI1ZR0qbGa3ftN7/va5vXTiMelhzP8Wtyurk49oxa/xZauUAybVjDdWnBHnjDYhB/x9/j2luqEpKjYMpmQcFwDwhzaRUPO/MMJJLj9DIo23IckmZXtlfvya0DEcK7lEbTjXUiJhjLdMkWD0Qulv0auc23ZDJAKBej0pFJpfm9iuveuXbWSQOF50XViz6D6H+gFuxPWFigtnvHM7hdojnDly5Q7Z0ZdooihIAPWj2zUOw0cCmnTQUGGl5GxtGhHrlNSfkyvtS2SDxDfzN/Dg1Xt++bj5IZG4Msq9BWxzQBeow0s+Xmonnu4fg2gBoFUQpCndL6xXaePCSrs/6AGsbFUaGgH1tC4HhJSb/Y2dQ6G7OHlAr/UrjGE2ZVaL/G83XFy1MDelUkB0YYZkktBjuA1ZKMuiKwYQUUdRbPEYEPdVejOnJLroj1SnqLpYuhdO9iNfoa+wusq6b8KRD9X+LQpwGdH8w51lDdUi9wgVY7IeybLZkIbwA2MK0GsSUgV/CY20qOTU0qK3Ra9+jNbmr7T1G/qsArLS+mU3S4S9xxFFO2xjVXL3UrYbY9cZWniPTCRhsop2hHHg9x4OIXhbfPEQ6R+8gSws4A2rj57bhtZrpw3C4c19JZ2mBAOaGSasggcWw4Iv2C3ue9IQjAkfuT+muB7r+dcYuNMYA8Hrunnt0J0wi/HpOV2sgWJX8vy9zwNQjPrmbPIk9Oq8C0k3oNMl20oeg6ynm2rRcVuLRzoM=
  template:
    metadata:
      name: ghcr-essentia
      namespace: essentia
    type: kubernetes.io/dockerconfigjson
