# hermes-backup IAM 유저 자격증명 (aws/iam.tf가 발급).
# 재봉인이 필요하면:
#   terraform -chdir=aws output -raw hermes_backup_access_key_id | KUBECONFIG=~/.kube/config-json \
#     kubeseal --raw --cert k8s/sealed-secrets/cert.pem \
#     --name hermes-backup-credentials --namespace hermes --scope strict
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-backup-credentials
  namespace: hermes
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA4uoUP3ohK2QVxViUrpNRx1mu535jZCqfhKRGhpJDfh+kSWxYp9OzfLRfS5c8J7+vix0VqtHuftg+eptiD0Fp0BPULRUP47JUpJfOZHWvc4hnfLLsT5dJyFohTEO31LzENC+XbZXI1He6gJ6536PMKErrq6mXEkU+VA3llPLOeVAEj5nnR0a+nSJUU7a0GFQQuF57pCkCSmewTVrnuduTWo9D7A6uYa4zNbMyiCZ/+ivYU509RwBSbU3GzOxk62qZXp31xDk9T5OgFkBCBlApJGUou/yrG7CTxZKlzp6hhz2SSJ6gUgnyUmLrzO8vS4hjObzNVNtJzpBtFLZB73sJYJaF5zBm9eoK4YyonDADtJ5VBUKrSniP7BMdfXeBgrt6w5YwfTDxP7dk2MU6Dot4sOM9B43iBH4WSCb7caveshw+AJGXbkjIj39jXXySN0V9aUfXPaTzY28FSBiPNeBWmF2yBtBCefOaGF75LuOx4UkjccOUfp+BTZeXPCPP4/m+NPpGVq+32YyiVuqh5H+d//ZfL2oPwSGSflKd+DK/10295T6LSCt2QfRqTWDI+DSgg0ivv/aGDmZMi4m0tM5hq/E+m0uJOLGEDNMGVOIAy5W9wfyo8JsfyeJQXCS40ix8LybsvzveWTyhn4wEUaag3wj2vh53ZoonLKN3xE0kW3VAWFKYDjv99LGX6AVRBptyLhh7WwKhF28M0+ltyg65x2XQlbQ==
    AWS_SECRET_ACCESS_KEY: AgANCHQLryCYIZ3YxcCjJecwi/gZCJOskDHwawWbX51HxVXbamoPdK/0vN8+zsvwXX1DlLsYWHJziOJZ2l4qn9UtMWV+LXOlxNpuMF9xrJtRHxhXMhsXSQ/AYHZ5VqXJpvUItQVeEFHMLXue20Z6Z3PWJiPd8a4bf4ZiUNFvRh8TTPGtIXFzqUwj7MGqoxTm/l9c7nsECt0pqjSJpqqOQWmHhz7kwVfGEPW7O2CuIfXyMTThsDYJengYKs0yfpQTqb88lo7uzcXDo3bgq0ZkPWfcyVUOVWdJQvAF79YWrFtxpKuXBLiIasJo4AxWk9cnsEVtWQ4rQYOq6+khxzcIps4TzCCAsJ7tuaFgWjQ3N3CfR/tENJMs0hWuDKu9GLemJFcf5PqdtX9qMulP/lai2UpF18sN371y2gZAuYnAAGtxk90hQ3h3sHrbO68LcFrWp3VmWgTZhXqX9NFFpUeZgMz4ECfAZM1ZzgksfxvaTGTMX+cmbYN9VsKtFeUpJr/v03LA52z4DuCaNDj5Cd1julmfl2mKp+rNsYK4lxbUhTHx2BHwBZxRWgFLObGVyAHMtrvV69uUjgaVW3cHoZhzls2Tndyw2PMT/NFckXE7ukNbSK5FTCVOoQ3abU2iIv4D9d5WMuO1o2kQZjesFkdNsV3r0tgmEZYpzfdMcku+mBpQBh9IGdwVVKd0/8YDcJT5zjA1X17oXN2bKKQXYejfqWLb5Xg6VzpGku3XdZ98MBnZXwXfdzXCd8nn
  template:
    metadata:
      name: hermes-backup-credentials
      namespace: hermes
    type: Opaque
