prometheus-node-exporter:
  dnsPolicy: Default

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path-hdd-samsung
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    nodeSelector:
      kubernetes.io/hostname: json-server-1
  ingress:
    enabled: true
    hosts:
      - prometheus.json-server.win
    paths:
      - /
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns01
      traefik.ingress.kubernetes.io/redirect-entry-point: https
    ingressClassName: traefik
    tls:
      - hosts:
          - prometheus.json-server.win
        secretName: prometheus-tls
