apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: essentia-web
  namespace: essentia
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - essentia.json-server.win
      secretName: essentia-web-tls
  rules:
    - host: essentia.json-server.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: essentia-web
                port:
                  number: 3000
