---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-account
  namespace: factorio
spec:
  encryptedData:
    token: AgCeqaCeUX4Tx028daRLjHv8eV12cAzfiuE6TQ0+XFimSfJY8EsSyFfNCNhj0xholv0f2u2F98NGc6iEgmaEZ/hoRqsd32F+04J8oQyICwWl1PItXsU1TLiRgrIh3ASBIZEzluU4txPv0FGl1V6KRL0aCm/fXwF+ylFTf/IqMiYYS/8eC76k9nvIxljtBcoQucdHM36VOvZvHLqEtScdwKdZ0sXiHhdlviagfr+jaqajk6C75dd42EnRvCu3lCiYZcYJVcms+CFFiNB3U4Q7ObyaWB8Oc6236Avl4ckEUGvA1dtuxAevV/CVaTrChizxXj+4xgNLldDD75VLnLb/+4Fi+FdYmYz5TjNNHeTlpSPGezEvZ5zi0CwsKA6V7X2/1nhAGQ88LtKlUGz+/cc/Y0JShpMKAVOdQxIfmTXF0wRGXFSJkrSd7BgP9EH8UpxXixvHxiy6mSo439zBadtIazaGXh8nHL10aDmiG8Q+k1aqVLuUra4/G7/oUPSr2om32E05Jz5M1csjXpwpDMQB8AjClgNZ2uQRMSqhH/SN32jr60KA8IYoI+DLmenTz7x+Lc1i5S4A0wPhmcVfjvag99m27LKJptEgEp34wTms/Pf0q5O+UzoyXcd0oNF6G+A7i3+aRfggHpdu4htooTsFzEzmqiT0eeXjIskNhIo2Q3cQ2rsskcp+GqQHypJVayjqxXPnjIPHp6rS1Znxx97O/vuhZwYeHFlKEm7ZFHenGyw=
    username: AgBRS63xARkiQSdmj1XJ0RG03HO+Bi9ZdeQ/5EohSjyK3kHVCgE/HQd5T487LR14s0lAd/TGuWggES1hfPHG7O6ZmQdAhWgm6rKmHwoP/cr3PuMB/dvFACeVceuUz6jxBu+9eWnCV0HuIWj43YKihb6ewtVZBiGTdEm/m8CVr9GeeTeMhxUo/VX/fO6oYd7utYWvJAXMjkwT67K2pGN8kjm4xLvvoUM6Psw5FWEGndoN7qa2khSScSGVEP09wlUtgaCcUgpFqZE3a/HfadZTyAUJKyid5rywfI54C5GI0t+oClyGivtU8K3M1wdXbqvOppQd9F7SC8NjXuAdUgqkZafmbFgh/jvctUGm28EESBHmITvRhyxfTZfFtm+KqwWyfTsjlrJ5vHmQRPHoKAnGq1CQ+jdF9Ue9BFdPkpQk9at3mqjlAAiep7OhdbjcZkHyo0vrzdgfi77nNJEdUbm8TUtS8a29u0CIaHYh6UoZsTqD71hQG/2U5ToNlhHTW2h7uGyIdQHVyIowGLptrAvBEe4eFiXXf6S20U2qRlJPF06OCJYZbvcrhwa6lMk6aS2ljwls397XoUqF2voknWOCjlWqC8viH3wNOyvoR0ghJ/eeubeHUlb8a01cHSGd/6E7ZyGB/N023sE5MgWi6sMSQD3spmVZ0QnpzHlRhLzy5ehz1vB04cOKTRQ4buwtp++I7TNm8A/ObfL5TQ==
  template:
    metadata:
      name: factorio-account
      namespace: factorio
    type: Opaque
