apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gbrain
resources:
  - caddy-configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - sealed-secret-api-keys.yaml
  - sealed-secret-github.yaml
  - service.yaml
  - sync-cronjob.yaml
images:
  - name: ghcr.io/manamana32321/gbrain-mcp
    newTag: latest
