---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gbrain-api-keys
  namespace: gbrain
spec:
  encryptedData:
    OPENAI_API_KEY: AgBZHQFXCr8gysucAi6Qx++Tcn3MGbWMfMarDXtIneBf7ZU7g7h/Y0KZrmlXF5Z40ui0fyAVX00HJqqwN974fyzjDbjKIdY0EaQUjfMtMM0Hu0n21Ct+H3vnSuYv6WDTA6SjaJTGQrDclGvGltnR+kbZSsZmllaGWa8ACvAdCf2C54mh5cC6LjuJlrUPBoKPzchh79dufBNL/O5AvMlG7qL3e5a17vOfzUdiQkrfdFgGRWhkcNtTCoBIudEaEzSh6s4mEmwKjSIEtlYfHr8XbUSAvHr595xLOe5P0mygPd3SojHA7oqFhU5gFmDL8YVRcsAK2rBuAOxigRFSCsoAiBpypbroauSyVDRXagXsOTBsdWZlDoY/t1AOLRSeSiSxfyQFey31LApI/EhuUeVd+4Le7APv4vsw1C80gNJFcooVpf8OX7KRvP9mmDDVWu32w8tM6jK3R4Yy1WTGrHqe4dqF9xcaQILkQ0aXlhF+F7vrfJ3R8a65UjOM7JsH60iwdJk7jARTorSRnGC3MpQd7FDvzw5JBJF9oRk5ki05yT4Mc2EV4bTOJ2kE9uu+KlWfNflxSCH2JDZV3U2hFtpTTQmj4H9aJ3t6qBqZK8rx5FLubZ/mYua9e2AbXNL6ZzAmAyjlDv59/f0S6w1IF0ZGH1AVe++ViVW45D3RvkIOsvCSkIKkfLmY9D5ajmMIv9FznUY=
    ANTHROPIC_API_KEY: AgBLOTVG2U6Bb/AF4PTE5AoKh/q23lx8SNrIGzClkpvjO0fp4XpdSff4NDOypXEg17+8n7/eYkTbUCgpv80SXYkWPWkOuItLuUco+eS7XqaQISUcFIS6aF+KItVkGbhxIoej1EzJJ9w3UfFqNil2p9lxh1Xxz7zjLzYO8BJlk4le/z7q0P7djK6Gn+xlkOpLz13erQL0bdNsAiZy2TEUwV7ijf5/KtkOyjTaw7BLVIuKFUO5txrDHSToLZctl2GnqDn2FTeiRF58mil9Je72HDiovfrcnNjVPfkRCYIXiUql/Ck7m1sJqZVtKruu0aUgsli2UZCJs80I92ZSO6gqQ5wL6wq0KFGuhyVxVHH/0cZNOTqVbTApVysnghP0c/VWR2derJ8od04MlslJsC8+8lv+KzRrNYGnnoG5izLbrJhxJ34zKZ3VCFWS2AD5/pYAnY7MGvR2lHj6f9JaejtOq+mlJTijj9aBp+oaVpDVOi3kF8czzg+3FWmrydYY7PCGTCiIy/BJmY0PEBzQpSRWZJ0KoXsyphgU5vpGKHHq7Dnoff8//HqHZrFzrSjnF+IqRG9VKmwmSVSQBeZffuLd5YhZt0Mib0e4/FGPKu6pD0Z7GbSkXveYQfWz45UZ3rwQWLNFB50LmwoWuv8TdicGb7EqZ8B46kP4XIg9ChrP3vO85zZ4s0j6GrqEONQlzmelEi0=
  template:
    metadata:
      name: gbrain-api-keys
      namespace: gbrain
