apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/manamana32321/homelab
    targetRevision: main
    path: k8s/argocd-image-updater-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
