apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-hdd-samsung
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/manamana32321/homelab
    targetRevision: main
    path: k8s/storage/local-path-hdd-samsung
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
