apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/manamana32321/homelab
      targetRevision: main
      path: k8s/mosquitto/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: mosquitto
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
