apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/manamana32321/homelab
    targetRevision: main
    path: k8s/shared-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
