apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    additionalArguments:
      - "--entrypoints.websecure.http.middlewares=kube-system-bot-block@kubernetescrd"
    experimental:
      plugins:
        blockpath:
          moduleName: github.com/traefik/plugin-blockpath
          version: v0.2.1
