global:
  envFrom:
    - secretRef:
        name: authentik-secret

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns01
      traefik.ingress.kubernetes.io/redirect-entry-point: https
    hosts:
      - auth.json-server.win
    paths:
      - /
    tls:
      - secretName: authentik-tls
        hosts:
          - auth.json-server.win
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 1Gi

worker:
  replicas: 1
  startupProbe:
    exec:
      command:
        - ak
        - healthcheck
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 30
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-secret
    secretKeys:
      adminPasswordKey: PG_ADMIN_PASSWORD
      userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD
  primary:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: longhorn-ssd
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 512Mi

blueprints:
  configMaps:
    - blueprint-cloudbeaver
