---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-saemate
  namespace: saemate
spec:
  encryptedData:
    .dockerconfigjson: AgCqyt+I3pxZE/vwHTpeNBUq5IGYr/QAPbXOcnjWE0DiUQnHwatSBZQZYVPocYO/XXtDQ0YFRQPxjwBZcM6iS5sFn/olS+jBN+3a5xxVlRoMHogM6nZ8wrfK2NDGQJ1Nazcxs2aWB9iN+7bW/Kl5/niBmztwb17KQia1+wdZvFtoaovk/bdIuR0x5TYnCih3YcZxjro20yN48wAKaoKjNk0OuT5dHkL4CE0JOPDFwx7G9OY+c3mwEIbRyvwQtvCWSpI62pwF9VQAHOwHuyK+n7Ecx4maCZhbkKQ3WMKrvkhGGXyDiI9TJWgl7YoRMA3s5csr+Z28qYBg5g6aymBzARw7RwqiFLF2KRZgp7krRUE3tVxqJuGQFH12y8sTmrcECYpNBs0RAMD1zIK+XoiT7wE9EhMFsSTINh8IsqGyItqhL+Y8OJAOFppUpfMpDgM+bP3p4TftWO4vgsID+yVJfWa0Ng62YNYSi4FVcsECfRGXH3epTh5Qq/+koPT67tR57vv+xsxFFEGfAmMHwlIwOJDqBYZZ+x1pAQPfkpncnmKFLbha8JQcXlhAlERMEGlAqM9JknZkYPdjKZbKkxh+/R+SqIkxpSSXBXTqpKzcEB5Lrz8frJLDS7BA+Spv7ToFL3QT77bcR3rRp8MdnE0KgaYbiw+FvwrAI99u8C7x1ThTUX1rKuUdAW2ZsDp7Wm5DRY2Dg2EBdCezpsLz0Xc0MAcaI9OI9YGN3/WfeP+naWCgW/Wcgv9MbJV5le/FdZJZXi+GpQfCtukgLO6HnP38GKXB0FkzGZ0gx+0dHTVMb+jp78irJX61ZB0rVv4uWAyh878VEP+3OwJBrUA7MjSr
  template:
    metadata:
      name: ghcr-saemate
      namespace: saemate
    type: kubernetes.io/dockerconfigjson
